### ISSUE TITLE
Show Steps in Title

### ISSUE THREAD

**Issue by MovingGifts** [sorich87/bootstrap-tour#100]
In debug mode, we see: ("Step " + (_this._current + 1) + " of " + _this._steps.length)
Is it possible to have an option that if 2 or more steps exist to optionally show them before the step title as: 1/3 - Step 1 Title, 2/3 - Step 2 Title, 3/3 - Step 3 Title?

And the tour option would be Steps: True?

**Comment by AdrianHastro** [comment]
[ASK]
i have new template at file template.htm.
i want to change my template with include file template.htm.
How can i do that ?
