### ISSUE TITLE
Move in correct direction when skipping over step

### ISSUE THREAD

**Issue by fczbkk** [sorich87/bootstrap-tour#112]
Let's say I have three steps. Steps 1 and 3 are fine. Step 2's element is missing. When I try to move to next step from step 1, it skips over step 2 to step 3. But when I try to move to previous step from step 3, it skips over step 2 back to step 3. There's no way for me to get to step 1 anymore.

When skipping over a step with element missing, it should check the direction of the skip.

The question is, what should happen, when previous skipping over the first step. When skipping over last step, the tour ends. I guess when skipping over first step, the tour should restart.

**Comment by ashwaniare** [comment]
How can I skip a step based on if the step element is present or not, I am trying to do something like:

`onShow:function(tour){
if(somecondition){
     //do something if the element exists
}else{
    tour.next();
}
}`

This is stuck in a callback loop and says **Uncaught RangeError: Maximum call stack size exceeded**.
