### ISSUE TITLE
Is it possible to "pause" a tour?

### ISSUE THREAD

**Issue by tankchintan** [sorich87/bootstrap-tour#129]
Currently I am trying different approaches for pausing a tour & then resuming it. One of the approach involves doing `tour.end()` when the pause button is hit & then on resume I just do `tour.start(true)`. This approach worked for the library `version 0.3.0` but after I updated the version to `0.5.1` it has stopped working. 

You can check this behavior in jsfiddle http://jsfiddle.net/tankchintan/fdcXR/7/

Another approach is to get the current step/state & then just use `tour.goto(curr_step)`. But unfortunately the `tour.getState()` & `tour.getStep()` are not working returning `null` or `undefined` any time I make a call. This behavior is also seen in the jsfiddle I linked.

**Comment by fmichea** [comment]
Hi, is this still possible? Based on [documentation](http://bootstraptour.com/api/), ``pause`` and ``resume`` do timer manipulation now:

- ``pause``: Pause the duration timer. It works only if tour or current step has duration.
- ``resume``: Resume the duration timer. It works only if tour or current step has duration.

My use case involves pausing the tour in a few places to have user interact with UI (fill out forms) to guide them through the main UX. I guess I could do this using separate tours and manually stepping through them, just wondering if it's possible to do this all in one tour.

**Comment by Vitoza** [comment]
I need in pausing a tour & then resuming it too. To interrupt tour and then resume it from the last visitted step. Is it possible?

**Comment by bardware** [comment]
I want to step through a tour manually and pause (save state) to continue later. `.pause()` only seems to work when `duration` is configured.
