### ISSUE TITLE
Placement option for 'Center'

### ISSUE THREAD

**Issue by oravecz** [sorich87/bootstrap-tour#150]
It would be nice to center the step in an element some of the time.

**Comment by fluxsaas** [comment]
i have the same issue, the element i want to describe covers more then 2/3 of the screen. the tour popover does not have enough space to be rendered. 

it would be great to display the popover in the `center`, but still use all other options e.g. to highlight (with backdrop) the specified element.

e.g.:

![screenshot 2015-08-03 14 46 51](https://cloud.githubusercontent.com/assets/13223/9037729/6b10fde0-39ee-11e5-9ff0-a1c0e8821996.png)
