### ISSUE TITLE
Bootstrap 3 hidden-xs class

### ISSUE THREAD

**Issue by 2piix** [sorich87/bootstrap-tour#153]
I have a panel which has the class "hidden-xs", so that it does not show on very small screens.  I would like to add a tour item for the panel, but I keep getting:

"Bootstrap Tour 'tour' | Skip the orphan step 2. Orphan option is false and the element doesn't exist or is hidden."

even when using a large viewport.  Is this by design?  Am I doing something wrong?  Or is it a bug?

**Comment by AdrianHastro** [comment]
how to skip step if element not found?

**Comment by ladhadha** [comment]
Hi @2piix, I got the same issue, how did you fix that?
