### ISSUE TITLE
backdrop shows white block

### ISSUE THREAD

**Issue by mehtatejas** [sorich87/bootstrap-tour#183]
When parent container of tour contains position relative, then tour container is displaying white block as attached.

![screen shot 2013-12-29 at 10 31 50 pm](https://f.cloud.github.com/assets/1712903/1819695/063deed6-70ab-11e3-8e01-2c70dea200ea.png)

**Comment by hugohcn** [comment]
Hello there,

I'm having the same issue here! Does anyone solved it? If yes, could share the solution please?

Thanks!

**Comment by goethewins** [comment]
This does not work.
.tour-backdrop,
.tour-step-background {
    z-index: 3;
}

Why hasn't this been integrated into the core code base? it has been over a year hasn't it. When will this be fixed? v0.10.2 ?

Please advise. I need something that works. Both this and intro.js have the same problem.

**Comment by asadiqbal389** [comment]
yes..tis does not work for me.
.tour-backdrop,
.tour-step-background {
z-index: 3;
}

**Comment by El-Mahbub** [comment]
I found a solution for this problem. 

-If you want to background white with transparency, just add this on your css file :

.tour-step-background{
background:white; 
opacity:.5; 
filter:alpha(opacity=50);
}

-If you want a full transparant for backdrop just add : 

.tour-step-background{
background:transparent;
}

Hope this can solve this problem. Thank.
