### ISSUE TITLE
Unable to start tour, always get error: "Tour ended, init prevented."

### ISSUE THREAD

**Issue by borfast** [sorich87/bootstrap-tour#184]
I'm using version 0.8 but I don't seem to be able to start a tour at all. I activated the debug option and always get the following error message on my console:

`Tour ended, init prevented.`

Unfortunately it doesn't say anything else, so I have no idea about what's wrong. I am including both the CSS and the JS file in my HTML code, and stripped down my tour code to the simplest, just like the example on the home page:

```
// Instance the tour
var tour = new Tour({debug: true});

// Add your steps. Not too many, you don't really want to get your users sleepy
tour.addSteps([
  {
    element: "#btn-1",
    title: "Title of my step",
    content: "Content of my step"
  },
  {
    element: "#btn-2",
    title: "Title of my step",
    content: "Content of my step"
  }
]);

// Initialize the tour
tour.init();

// Start the tour
tour.start();
```

Am I doing something wrong?
Is the error message I mentioned at the top something with a common / well known cause?
What could be triggering it?

**Comment by doganmeh** [comment]
in some occasions `tour.restart()` did not help; so I had to clear localStorage for `tour_current_step` as well:

` localStorage.removeItem('tour_current_step')`
