### ISSUE TITLE
Element from nav doesn't show correctly

### ISSUE THREAD

**Issue by igo** [sorich87/bootstrap-tour#189]
When element is set to an item in navbar and backdrop is enabled then the text of the menu item is not visible.

**Comment by jcorreia** [comment]
Im having this problem also....

**Comment by bnussey** [comment]
+1 to having this problem

**Comment by sorich87** [comment]
Is https://github.com/sorich87/bootstrap-tour/pull/335 and acceptable solution?

**Comment by ignaciolarranaga** [comment]
+1

**Comment by mjp1** [comment]
@joelmats solution worked for me too! Thanks!

**Comment by aurel-tackoen** [comment]
I had the same issue, the only working solution was to add this on each step : 

          onShown: function (tour) {
            $('.tour-backdrop').css("opacity", "0");
            $('.tour-step-background').css("box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0.5)");
            $('.tour-step-background').css("-moz-box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0.5)");
            $('.tour-step-background').css("-webkit-box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0.5)");
          },
          onHidden: function (tour) {
            $('.tour-backdrop').css("opacity", "0.5");
            $('.tour-step-background').css("box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0)");
            $('.tour-step-background').css("-moz-box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0)");
            $('.tour-step-background').css("-webkit-box-shadow", "0px 0px 0px 4000px rgba(0, 0, 0, 0)");
          }

and some css : 
.tour-step-background {
  background: transparent;
  border-radius: 0;
}
.tour-backdrop {
  opacity:0.5;
}

This basically keep the backdrop (preventing from click etc) but make it transparent, and make a huge box shadow around the highlighted element.
I reset the original backdrop between each step so it does not blink.
I'm not sure about cpu/memory usage (and you can setup the shadow to be smaller than 4k if you know your max res)

**Comment by rapcal** [comment]
@Phr33d0m thanks a lot for bringing animate.css to my attention. A lifesaver. Thanks!

**Comment by tm1000** [comment]
The solution is definitely in https://github.com/sorich87/bootstrap-tour/issues/166#issuecomment-32213509

which turned into the API key called "backdropContainer". Which you can find in the documentation. Once you use backdropContainer correctly (placing the background container within the fixed PARENT) it all works. I wish this was easier to find.
