### ISSUE TITLE
Internet Explorer - script65535 invalid calling object

### ISSUE THREAD

**Issue by alexandreneves** [sorich87/bootstrap-tour#218]
I keep getting this error while using IE (8 and 9 at least).

File: bootstrap-tour.js
Line: 274
Code: switch (toString.call(step.path))

I got to fix it using Object.prototype.toString.call(...) but I'm wondering if there's something I might be doing wrong. I don't really want to edit the plugin's code : )

**Comment by neelsbr** [comment]
The Same issue throwing in IE11. I am using windows 10
