### ISSUE TITLE
Standalone incomplete

### ISSUE THREAD

**Issue by ksonnad** [sorich87/bootstrap-tour#232]
To get standalone working properly, I needed to add
- [transition styles](https://github.com/twbs/bootstrap/blob/e381635b1faf7480bcf54618804a62dd4a049a93/less/component-animations.less)
- [transition.js](https://github.com/twbs/bootstrap/blob/68b3e3f3be1d326474a7f3d2fbc82f349f7815fc/js/transition.js)

Shouldn't these be included in the standalone CSS and JS?

**Comment by ocmobi** [comment]
I still have this issue when using stand alone in a joomla site that's probably using older version of jQuery and definately using older version of bootstrap v2.

I thought stand alone resolved all these issues by including what it needs?
