### ISSUE TITLE
Bootstrap tour wont show up inside of a modal unless you open/close the console [chrome]

### ISSUE THREAD

**Issue by castledoor** [sorich87/bootstrap-tour#233]
I was able to recreate this issue outside of my app

http://bootstraptourtest.site44.com/

just click start tour, then next and a modal should pop open, there is a step attached to #tour-modal, but you will not be able to see it unless you pop open your console (command + option + J), then it appears, it also works if your console is already open, just close it, and the step appears. any suggestions on how to fix this bug would be greatly appreciated

**Comment by harifaltoos** [comment]
Create a div under the main model div 
Then add Class or Id for that div 
use the Class or Id given for the new div in boostraptour
Its working fine for me..
