### ISSUE TITLE
Vertical position when position is 'right' or 'left'?

### ISSUE THREAD

**Issue by eliasisrael** [sorich87/bootstrap-tour#234]
Hi, I'm trying to achieve a placement for the popover to the left or right of an element that is rather tall. It's actually taller than the viewport.

Right now, bootstrap-tour is placing the popover vertically centered over the height of the element, and then scrolling the view to the top of the element. This causes the popover to be positioned offscreen, outside the viewport.

What I'd like to do is ensure that the vertical position is centered to an area no taller than the height of the viewport. Or, better yet, enable a position of 'right top' or 'left top', where the vertical position of the top of the popover would be aligned with the top of the target element.

Is there a way to do this that I'm missing? Thanks.

**Comment by Jarvizx** [comment]
Hi, any solution?
