### ISSUE TITLE
How to set to path with https in second step???

### ISSUE THREAD

**Issue by Goonathan** [sorich87/bootstrap-tour#249]
I have this code:

jQuery('document').ready(function(){

    var tour = new Tour({
        //debug: true,
        steps: [
            {
                path: "/",
                element: "#qbien-Keywordsid",
                placement: "bottom",
                title: "Bienvenido a Qbien!",
                content: "Step1 ",
                onNext: function (tour) {
                    jQuery("#qbien-Keywordsid").val(keywords);
                }
            }, {
                path: "/onepagecheckout/",
                element: "#bill_address_block",
                placement: "top",
                title: "Dirección de envío",
                content: "Step2"
                //duration: 5000
            }
        ]
    });

// Initialize the tour
    tour.init();

// Start the tour
    tour.start();

});

How to set to path with https in second step???
 (path: "/onepagecheckout/" is https://../onepagecheckout/)

First step is http, but second step is https

**Comment by sorich87** [comment]
Fixed in #417.
