### ISSUE TITLE
Next Button not working

### ISSUE THREAD

**Issue by neehakale** [sorich87/bootstrap-tour#253]
I am trying to create a bootstrap tour with standalone bootstrap but when I click Next even on the same page next does not work. It disappears. What Am I doing wrong?
 $(document).ready(function() {

  $(document).ready(function() {
               // Instance the tour
               var  tour = new Tour({
                   name: "tour",
                   steps: [

```
                  {

                      element: "#Name",
                      title: "Test ",
                      content: "Create a new Test Group"
                  },
               {

                   element: "#creteTest",
                   title: "Test ",
                   content: "Create"
               }],

           });


           // Initialize the tour
           tour.init();

           // Start the tour
           tour.start();

       });
```

**Comment by ayisharu** [comment]
I have the same problem. I am using v0.10.2 standalone.
The NEXT button is not working. But when I go to a step other than the first one and click on the PREV button, that's when the NEXT button will start working.

It's just weird.
