### ISSUE TITLE
Migration under MIT License

### ISSUE THREAD

**Issue by bdauton** [sorich87/bootstrap-tour#257]
Hi all,

As you know, Bootstrap 3 is now under MIT license. To follow their license and to allow GPLv2 projects to use this awesome bootstrap add-on, we need the approval of all contributors. To do so, it would be very cool if all of you fill this form: https://docs.google.com/forms/d/1U6Biw2jU2DFeNKTuy9F2jCMcvsEoI8cwbgeVj6vnWj4/viewform?usp=send_form

Thanks !

**Comment by mike-potter** [comment]
Bumping this issue once more.  The current Apache 2.0 license prevents bootstrap-tour from being white-listed for inclusion in Drupal-based distributions.  I'd really like to get rid of the CDN link and have this library included in the Open Atrium distro.  Is this issue dead or is there any way to get this license changed to MIT?

**Comment by sorich87** [comment]
@mike-potter lack of time to complete that is the issue :(

**Comment by mike-potter** [comment]
@sorich87 is it lack of your time, or lack of response from some code contributors.  Seems like other projects (like Bootstrap) have been through this and there should be ways to deal with people who contributed code but don't respond in a timely way.  

But what's the real blocker here?

**Comment by sorich87** [comment]
@mike-potter 

All the biggest contributors are ok with the change. But, as you noticed, there's lack of response from some other contributors.

The solution would be to audit the commits from these contributors to see if their code is used, contact them individually and revert the commits if no response.

That's why I mentioned my lack of time. Do you want to do it?

**Comment by mike-potter** [comment]
I can't take over and actually "do it", but maybe we can open this up to get you more help.

As a reference, here is the very long related thread covering this same issue as it happened to Bootstrap itself.  You'll see that it was started in a similar manner (Drupal distros wanting to use Bootstrap).  Had a lot of side-tracking discussion of MIT vs Apache and GPL2 vs GPL3 stuff.

Ultimately they were able to contact almost all code contributors and then finally reverted the code from the small number of people who said no (although then it looks like they just committed similar changes/fixes back, so not sure how "rewriting a commit" really works when it's a trivial commit).

In that thread, they also recommended using https://github.com/beberlei/license-manager.

Maybe you could set this up in license-manager somewhere (never used it so don't really know how it works).  Or, at least set up some sort of public google doc with the list of contributors so we can keep track of who has said yes, who hasn't responded, etc.  Then maybe we can restart this effort and really see what commits are left that might need to be reverted/rewritten.

**Comment by sorich87** [comment]
Agreed. It would be great if anyone can help with that.

**Comment by marclaporte** [comment]
Hi!

As we saw in these two cases, it takes a very long time, but eventually, we succeed.
https://github.com/twbs/bootstrap/issues/2054
https://github.com/nostalgiaz/bootstrap-switch/issues/347

We need to start to make sure new commits are in the new license, and then we work backwards to get all the previous commits. I just added two pull requests for this.

Big picture steps:

1- Announce intention: all new commits have to be dual-licensed MIT and current license. (Done)

2- Contact all the code committers, which still have code in the current master. Template example here: https://tiki.org/Bootstrap+License+change+request

3- Get them all to agree (The best is to vote +1 on this thread. An email works as well )

4- If some refuse or are unreachable, rewrite their contributions

5- Release new version as MIT

**Comment by marclaporte** [comment]
Here is a copy of the spreadsheet with previous approvals:
04/05/2014 16:39:08	YES	LostCrew
04/05/2014 17:18:51	YES	fczbkk
04/05/2014 17:29:14	YES	sorich87
05/05/2014 09:58:24	YES	emmenko
05/05/2014 13:58:25	YES	martin-g
13/05/2014 18:03:22	YES	test
14/05/2014 08:54:52	YES	s7anley
19/05/2014 10:23:20	YES	mm
04/05/2015 19:09:12	YES	mike-potter
16/05/2015 20:18:37	YES	brexis

And some stats:
https://github.com/sorich87/bootstrap-tour/graphs/contributors
https://www.openhub.net/p/bootstrap-tour/contributors?query=&sort=commits

To the following, please add +1 to this thread. Thanks!
@Genosite
@fczbkk
@sdizier
@SKAhack
@ivanov
@rhertogh
@11Hengjie
@ramatevish
@bdauton @forest
@mlissner
@kozak
@Esperancia
@tmort
@borski
@kaihowl
@arnaudbreton
@eliasisrael
@fabienpomerol
@javaguirre
@ma-si
@hfellmann
@ericdegboe
@usmanhalalit
@html5cat
@ragulka
@erwanjegouzo
@rolo
@edgardmessias
@TiddoLangerak
@msievers
@dannon
@reubenbrown
@Benoth
@KyleMit
@mattmcneeney
@pavarnos
@mareksotak
@aiccucs
@minrk
@gkorland
@evanleonard
@cvrebert
@Amli

**Comment by kozak** [comment]
+1 (also signed the form now)

**Comment by fabienpomerol** [comment]
+1

**Comment by fellmann** [comment]
:+1: +1

**Comment by mareksotak** [comment]
+1

**Comment by msievers** [comment]
+1

**Comment by javaguirre** [comment]
:+1:

**Comment by rolo** [comment]
+1

**Comment by rhertogh** [comment]
+1

**Comment by SKAhack** [comment]
+1

**Comment by reubenbrown** [comment]
+1

**Comment by ericdegboe** [comment]
+1

Le ven. 7 août 2015 à 14:57, reubenbrown <notifications@github.com> a
écrit :

**Comment by ericdegboe** [comment]
+1

**Comment by KyleMit** [comment]
+1 (how do I do that thumbs thing too - that seems neat)

**Comment by Genosite** [comment]
+1

**Comment by mlissner** [comment]
:+1:

**Comment by ramatevish** [comment]
+1

**Comment by ivanov** [comment]
:+1:

**Comment by edgardmessias** [comment]
+1

**Comment by html5cat** [comment]
:+1: :shipit:

**Comment by minrk** [comment]
:+1:

**Comment by pavarnos** [comment]
+1

**Comment by Hengjie** [comment]
+1

**Comment by TiddoLangerak** [comment]
:+1:

**Comment by aiccucs** [comment]
+1

**Comment by Esperancia** [comment]
+1

**Comment by marclaporte** [comment]
Thank you for all the support!  Keep it coming :-)

**Comment by sorich87** [comment]
Thank you! @marclaporte

**Comment by borski** [comment]
+1

**Comment by ma-si** [comment]
+1

**Comment by marclaporte** [comment]
To the users below, please, we need your +1  :-)
@sdizier
@bdauton
@forest
@tmort
@kaihowl
@arnaudbreton
@eliasisrael
@usmanhalalit
@ragulka
@erwanjegouzo
@dannon
@Benoth
@mattmcneeney
@gkorland
@evanleonard
@cvrebert
@Amli

**Comment by dannon** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by mattmcneeney** [comment]
+1

**Comment by marclaporte** [comment]
To the users below, please, we need your +1 :-)
@sdizier
@bdauton
@forest
@tmort
@kaihowl
@arnaudbreton
@eliasisrael
@usmanhalalit
@ragulka
@erwanjegouzo
@Benoth
@gkorland
@evanleonard
@Amli

**Comment by eliasisrael** [comment]
+1

**Comment by Benoth** [comment]
+1

**Comment by marclaporte** [comment]
To the users below, please, we need your +1 :-)
@sdizier
@bdauton
@forest
@tmort
@kaihowl
@arnaudbreton
@usmanhalalit
@ragulka
@erwanjegouzo
@gkorland
@evanleonard
@Amli

**Comment by kaihowl** [comment]
+1

**Comment by marclaporte** [comment]
To the users below, please, we need your +1 :-)
@sdizier
@bdauton
@forest
@tmort
@arnaudbreton
@usmanhalalit
@ragulka
@erwanjegouzo
@gkorland
@evanleonard
@Amli

Thanks!

**Comment by marclaporte** [comment]
@bdauton made this request so we consider it as a +1

**Comment by marclaporte** [comment]
@usmanhalalit you fixed a typo (not code) so I am removing you from the list. Thanks for your contribution!
https://github.com/sorich87/bootstrap-tour/commits?author=usmanhalalit

**Comment by marclaporte** [comment]
So here are the 9 remaining:
https://github.com/sorich87/bootstrap-tour/commits?author=sdizier
https://github.com/sorich87/bootstrap-tour/commits?author=forest
https://github.com/sorich87/bootstrap-tour/commits?author=tmort
https://github.com/sorich87/bootstrap-tour/commits?author=arnaudbreton
https://github.com/sorich87/bootstrap-tour/commits?author=ragulka
https://github.com/sorich87/bootstrap-tour/commits?author=erwanjegouzo
https://github.com/sorich87/bootstrap-tour/commits?author=gkorland
https://github.com/sorich87/bootstrap-tour/commits?author=evanleonard
https://github.com/sorich87/bootstrap-tour/commits?author=Amli

**Comment by tmort** [comment]
+1 - Sorry this took so long

**Comment by Amli** [comment]
+1 - sorry for the delay, I really need to reactivate the github notifications

**Comment by ragulka** [comment]
+1 sorry for the delay, did not realise you need my vote :P

**Comment by forest** [comment]
+1 - sorry for the delay.

**Comment by marclaporte** [comment]
Last call!

We need your +1 or we will have to remove (and rewrite) your contributions. A quick +1 will save us the hassle.
@arnaudbreton
@erwanjegouzo
@gkorland
@evanleonard

Here are your respective contributions:
https://github.com/sorich87/bootstrap-tour/commits?author=arnaudbreton
https://github.com/sorich87/bootstrap-tour/commits?author=erwanjegouzo
https://github.com/sorich87/bootstrap-tour/commits?author=gkorland
https://github.com/sorich87/bootstrap-tour/commits?author=evanleonard

Thanks!

**Comment by marclaporte** [comment]
The commit by gkorland
https://github.com/sorich87/bootstrap-tour/commit/fbbcaab909560a3e5faf2d3ef66a9cb5f76f0734
is in the file component.json which no longer exists

It is now in package.json, and the value has been changed, thus rewritten.
https://github.com/sorich87/bootstrap-tour/blob/master/package.json

So I consider this is resolved.

**Comment by erwanjegouzo** [comment]
:+1:

**Comment by marclaporte** [comment]
Evan Leonard's vote on Twitter:
https://twitter.com/evanleonard/status/666761164106416128

**Comment by marclaporte** [comment]
@arnaudbreton : you are the last one!

**Comment by arnaudbreton** [comment]
+1, OK for me. Sorry for the delay!

**Comment by marclaporte** [comment]
Super!  It took 18 months from the initial report. Choose your license well, because it's a lot of work to change on a collaborative project!

Related commits:
https://github.com/sorich87/bootstrap-tour/commit/e78b5b4174e8755539f39fe9c02401d18f6cc599
https://github.com/sorich87/bootstrap-tour/commit/c6697d85b3b94b7f6e8c1ae91a4f78df8965a4ca
https://github.com/sorich87/bootstrap-tour/commit/ae2d44bd51d15d74e6770e4db1b23c80937bfe3c
https://github.com/sorich87/bootstrap-tour/commit/19a7d711e5acc9c54e6688fb84d7490b166d3231
https://github.com/sorich87/bootstrap-tour/commit/876e72f3735e4d654f1b25f6c1fb0f4766aab39e
https://github.com/sorich87/bootstrap-tour/commit/f536263d22793fb7071ae5c52e1fc8415e66bf4f

Let's fix some bugs, and proceed to a new release :-)
