### ISSUE TITLE
don't hide backdrop when navigating between paths

### ISSUE THREAD

**Issue by ceejayoz** [sorich87/bootstrap-tour#278]
When we take the user to another path that has a couple seconds worth of load time, the backdrop goes away but you're left on the page while the next one loads. This is a little jarring for the user when the backdrop is always-on - it looks for a few seconds like the tour crashed.

It'd be nice if, knowing that we're navigating away from the page, if the backdrop could be retained until that navigation occurs.

**Comment by sorich87** [comment]
Should be fixed in latest master.
