### ISSUE TITLE
Support elements with fixed positioning

### ISSUE THREAD

**Issue by alexcasalboni** [sorich87/bootstrap-tour#288]
I'd need to bind my tour step to an element with `position:fixed;`.
I see I can easily fix it with a custom css like

    .my-tour.my-tour-N{
        position:fixed;
    }

where `N` is the step index, even though it's not so trivial as far as positioning (especially when placement is 'top' or 'bottom').

What about handling this behavior natively with an ad-hoc option?
@sorich87 @LostCrew

**Comment by tm1000** [comment]
The solution is definitely in https://github.com/sorich87/bootstrap-tour/issues/166#issuecomment-32213509

Which lead me to find this https://github.com/sorich87/bootstrap-tour/pull/335

which turned into the API key called "backdropContainer". Which you can find in the documentation. Once you use backdropContainer correctly (placing the background container within the fixed PARENT) it all works. I wish this was easier to find.
