### ISSUE TITLE
Redirect method for one-page app

### ISSUE THREAD

**Issue by Alexerson** [sorich87/bootstrap-tour#291]
Hello, 

I'm using bootstrap-tour with backbone. I re-wrote redirect to use Backbone History navigate.
Working fine but once the redirection happened, the tour stops.

The problem is around [line 252 in bootstrap-tour.coffee](https://github.com/sorich87/bootstrap-tour/blob/master/src/coffee/bootstrap-tour.coffee#L252):

removing the "return" statement make it work. Is there any reason why there is a return statement here ? 

Thanks, 
Alex

**Comment by sorich87** [comment]
This should be fixed in #418.
