### ISSUE TITLE
Backdrop isn´t working under certain conditions in Chrome

### ISSUE THREAD

**Issue by thomasf1** [sorich87/bootstrap-tour#313]
Hey guys,

I´ve been investigating why Backdrop doesn´t quite work under certain conditions in Chrome.

There is a change in Chrome 26 that defies the z-index if the parent is position:fixed.

I´ve been trying to find a solution and opened a question on stackoverflow:
http://stackoverflow.com/questions/25738825/is-there-a-workaround-for-z-index-of-child-of-positionfixed-not-working-in-chro

Cheers,
Thomas

**Comment by sorich87** [comment]
Is https://github.com/sorich87/bootstrap-tour/pull/335 and acceptable solution?

**Comment by sorich87** [comment]
Closing due to lack of response.
