### ISSUE TITLE
Works great locally but blows up on hosted site :(

### ISSUE THREAD

**Issue by nishantpant** [sorich87/bootstrap-tour#322]
Hi,
The tour works great locally, however when I deploy it to a hosted site, it blows up here. Any ideas or suggestions ?

  Tour.prototype._getState = function(key) {
      var keyName, value;
      if (this._options.storage) {
        keyName = "" + this._options.name + "_" + key;
        value = this._options.storage.getItem(keyName); <---- Uncaught TypeError: undefined is not a function 
      } else {
        if (this._state != null) {
          value = this._state[key];
        }
      }

**Comment by slh012** [comment]
This can happen if you pass a boolean to 'storage' in the global options json.
