### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by martin-g** [sorich87/bootstrap-tour#323]
Hi,

At http://bootstraptour.com/api/ there is a table with all available settings.
Few of them have confusing default values for their types:
- `backdropPadding` has type `Boolean|Object` but its default value is `0`, i.e. a Number
  Should the default be a `false` or the type `Number|Object` ?
- `duration`'s type is `Boolean|String` and its default value is `false` but the docu says that the alternative value is in milliseconds. So maybe the type should be `Boolean|Number` ?
- https://github.com/sorich87/bootstrap-tour/issues/241 introduced `delay` option but it is not listed in the table

**Comment by miksh7** [comment]
Same changes should be done in for the step options.
