### ISSUE TITLE
onShow(n) called twice when tour starts on step

### ISSUE THREAD

**Issue by LewisW** [sorich87/bootstrap-tour#327]
The starting step's onShow and onShown are called twice. This isn't always the first step in the tour, but the first step when the page is loaded.

**Comment by raelmiu** [comment]
Is this still an active issue?

**Comment by LewisW** [comment]
Not sure, lets assume not and I'll open another with more information if it is.

**Comment by deorayyan** [comment]
Hello, I think this is still an active issue.
I got similar problem that caused pop over window blinked on each step.

let's see this console log
![screen shot 2018-05-02 at 21 57 19](https://user-images.githubusercontent.com/32141530/39530857-0e15de94-4e54-11e8-9bbe-2822ea42c19c.png)

Please fix this issue.
Thank you

**Comment by camohub** [comment]
I have the same problem. I need to generate tour steps dynamically and if step needs to redirect then popup blinks after page load. Console catches onShown event twice. Second call makes that blink effect.
```
for( var i = 0; i < steps.length; i++ )
	{
		var step = {};
		step.title = steps[i].title;
		step.title = steps[i].content;
		if( steps[i].orphan ) step.orphan = true;
		if( steps[i].element ) step.element = steps[i].element;
		if( steps[i].placement ) step.placement = steps[i].placement;

		var regexp = new RegExp( steps[i].url, 'gi');
		if( ! document.location.href.match( regexp ) )
		{
			step.path = steps[i].url;
		}
		step.onHide = function() {
			console.log('onHide');
			alert('onHide');
		};
		step.onHidden = function() {
			console.log('onHidden');
		};
		step.onShow = function() {
			console.log( 'onShow' );
			alert('onShow');
		};
		step.onShown = function() {
			console.log( 'onShown' );
			alert('onShown');
		};

		tour.addStep( step );
	}
```

**Comment by ZachRHale** [comment]
I'm having this problem as well. Almost verbatim as @camohub. Should this issue be re-opened? I don't see a new one authored by @LewisW.

**Comment by BrunoSeijiMiyamoto** [comment]
I'm also having this problem. Sometimes the step window blinks and then it counts as another step visualization. Most of times it happens when the page needs to scroll. Sometimes it happens with no apparent reason.

![repeating steps](https://user-images.githubusercontent.com/25225410/49513766-347ae280-f879-11e8-9d2f-4cd37b0c52fe.png)

**Comment by AshwiniBetsur** [comment]
I'm also facing this issue. On every page scroll onShown() is getting called.facing this issue on iphone only...any solution?

**Comment by JohnPaul38** [comment]
I'm having same problem..this issue stil not fixed for  iphones  .still issue persists for mobile devices. OnShown function gets called on every scroll 
This should be reopened @LewisW
