### ISSUE TITLE
Restarting the tour every time the tour ends

### ISSUE THREAD

**Issue by yassersouri** [sorich87/bootstrap-tour#33]
Salam

I'm creating a tour. I want it to restart from step 0, every time that the tour ends.

How can I do that?

I've tried `tour.ended()` but that seems to be true when going to next step and when the user clicks end tour.

**Comment by elsheikh21** [comment]
I do not want the bootstrap tour to restart every time i refresh the page 
`<script>
		var profileTour = new Tour({
			steps: [{
				element: "#profile-info",
				title: "Welcome to your profile",
				content: "This has all of your information.",
				placement: "bottom",
    			backdrop: false,
   				animation: true 
			},	
			{
				element: "#profile-experience",
				title: "How experienced are you?",
				content: "In this area, add all of your prior jobs.",
				placement: "bottom",
    			backdrop: false,
   				animation: true 
			},
			{
				element: "#your-current-job",
				title: "Current employment status",
				content: "In this area, you posted your current status.",
				placement: "bottom",
    			backdrop: false,
   				animation: true 
			},
			{
				element: "#profile-education",
				title: "How was your education?",
				content: "Tell us more about your education, by adding it here.",
				placement: "bottom",
    			backdrop: false,
   				animation: true 
			},
			{
				element: "#profile-skillset",
				title: "Your skills",
				content: "The more assessments you pass, the more tools you have in your pouch.",
				placement: "bottom",
    			backdrop: false,
   				animation: true 
			}
			],
			storage: false
		});
		profileTour.init();
		profileTour.setCurrentStep(0);
		profileTour.start();
	</script>`
