### ISSUE TITLE
Bs 3.3 support

### ISSUE THREAD

**Issue by pyzen** [sorich87/bootstrap-tour#332]
It is not working with new Bootstrap 3.3 version. any tips ?

**Comment by jcorreia** [comment]
for me also but my background of the element is now completely white...cant see what behind..

**Comment by cmarfil** [comment]
+1 on this issue.
However @azaslavsky solution works fine.

**Comment by sorich87** [comment]
The issue was fixed in Bootstrap 3.3.2.

**Comment by eman1986** [comment]
I'm still experiencing this problem

**Comment by johntrepreneur** [comment]
So, the workaround mentioned by @azaslavsky to comment out line 511 partially works, but breaks the ability to specify other jquery selectors for the `element` property on each step, which for me was using the value `.myClass:visible`.

**Comment by johntrepreneur** [comment]
I ended up just using the standalone js files for the plugin, which fixed the problem and seems to look okay so far, but could be problematic since we have 3.3.1 already loaded. The ideal solution is to just upgrade as already mentioned, but this is my workaround until we upgrade.
