### ISSUE TITLE
2 different tour

### ISSUE THREAD

**Issue by alfredopacino** [sorich87/bootstrap-tour#336]
Hi, I have a tour in my site (no way O.o)
But I want also show a little single step reminder, for a total different reason (not tour related).
There is a way to use 2 different tour (I'm talking about the unmanageable localstorage..)?

Alternatively there is another bootstrap way to "append" to a div a single tooltip exactly how bootstrap tour does?

**Comment by sorich87** [comment]
To add two tours to a site, set different 'name' option for each tour. You can also use Bootstrap Popover.

**Comment by alfredopacino** [comment]
it's not that simple, two tour uses the same local storage "flag" to check if the tour is complete

**Comment by sorich87** [comment]
All the "flag" are prefixed with the tour name.
