### ISSUE TITLE
Opens modal behind backdrop of tour

### ISSUE THREAD

**Issue by rdandnayak** [sorich87/bootstrap-tour#339]
I have a tour showing a button which invokes bootstrap 3 Modal. and when I try to click and open modal while tour is still on. Modal opens behind backdrop. Is there any solution on this to disable the viewing area and not allow him to click on that button

**Comment by sorich87** [comment]
Is https://github.com/sorich87/bootstrap-tour/pull/335 and acceptable solution?

**Comment by sorich87** [comment]
It's an issue with z-index. You can now set the backdrop container to the step parent so that it's in the same stacking context. See #335.
