### ISSUE TITLE
bootstrap tour not working on mobile devices

### ISSUE THREAD

**Issue by sumitgulati100** [sorich87/bootstrap-tour#342]
i have added bootstrap tour on my website but its not working on mobile devices.

**Comment by sorich87** [comment]
What's the issue?

**Comment by eman1986** [comment]
I can confirm this, it smashes the popover to the right There is also a z-index issue if you move the contents over.

**Comment by eman1986** [comment]
I fixed the z-index issue on my own and changed the direction of the pop-up.
