### ISSUE TITLE
Element's background-color is getting overridden when using backdrop

### ISSUE THREAD

**Issue by PaulStevensLM** [sorich87/bootstrap-tour#343]
The `background-color` of the step element is being overridden when the `backdrop` option is set to `true`.

I've created a JSFiddle here http://jsfiddle.net/cyqpn9fw/1/

It looks like this is caused by the css class `.tour-step-backdrop`, which gets applied to the element.

Is there any need for this to override the background?

**Comment by Cruig** [comment]
I'm also seeing a variation of this - where it's positioning a `div` with some inherited color over the element I'm trying to highlight. Haven't been able to figure it out yet...

![screen shot 2015-02-23 at 9 40 10 pm](https://cloud.githubusercontent.com/assets/1849063/6343839/a6ab3352-bba4-11e4-913f-a352c89c3bc9.png)

![screen shot 2015-02-23 at 9 35 43 pm](https://cloud.githubusercontent.com/assets/1849063/6343822/6d22dd60-bba4-11e4-8bda-2500d536dbbb.png)

**Comment by sorich87** [comment]
@Cruig this should fix your issue https://github.com/sorich87/bootstrap-tour/pull/335

**Comment by rhertogh** [comment]
@sorich87 Hi, I'm having the same problem. It might look like the same problem as with the z-index, but this one is different. When an element has it's own background defined (e.g. it has the bootstrap class `btn-success`) it's overwritten by the `background: inherit;` line in the `.tour-step-backdrop` class style.

This line was added in 74f4d41bde90d8d44e1d028dd17c1a51c1553fdb but this commit was named  "Set backdrop to inherit the background color from the body element". It looks like it should have only been added to `.tour-step-background` and not to `.tour-step-backdrop`.

**Comment by sorich87** [comment]
@rhertogh please can you submit a pull request with the fix?

**Comment by sorich87** [comment]
A new way to handle backdrop has been implemented in 7f98180015f02231f5e9b9689785413fbe070454. Please test.
