### ISSUE TITLE
TypeError: e[b] is not a function with lates bootstrap.js

### ISSUE THREAD

**Issue by vasikgreif** [sorich87/bootstrap-tour#354]
I updated Bootstrap to latest version, also update BootstrapTour, and now I'm getting:

`TypeError: e[b] is not a function`
If I revert to previous bootstrap.js version I had (3.1.0), things work fine again....

Any ideas?

**Comment by neotropic2023** [comment]
Me too! No matter what I do this continuously gives me the same error. It is when it runs tour.init();

**Comment by neotropic2023** [comment]
Well, no response for this guy in 8 days, soo... moving on!
Next script please. See ya later bu-bye.

**Comment by jcorreia** [comment]
Hi,
im also with this problem...anyone figure it out ?

**Comment by garethbowen** [comment]
Looks to be the same issue as: #356

**Comment by CozyLife** [comment]
You can use the standalone tour JS with the bootstrap tour CSS file. That solves the issue without commenting anything out.

**Comment by sorich87** [comment]
Issue fixed with Bootstrap 3.1.2.

**Comment by CozyLife** [comment]
I just want to update this thread for the record. sorich87 has a typo in his post. The issue was fixed with Bootstrap 3.3.2, not 3.1.2. Thanks for the heads up, sorich87!

**Comment by mohandast52** [comment]
i have the same problem, did anyone solved the issue?

**Comment by Rajeshkumar300791** [comment]
i have the same problem, did anyone solved the issue? i have also used bootstrap new version.
