### ISSUE TITLE
error while implementing bootstrap tour

### ISSUE THREAD

**Issue by suriyagp** [sorich87/bootstrap-tour#355]
![error_at_step](https://cloud.githubusercontent.com/assets/6812243/5568657/d00af808-8f86-11e4-9d0b-ff8a155d8ee2.jpg)

**Comment by VirtualLegend** [comment]
Same issue here

**Comment by josephlewis42** [comment]
This is on the homepage of the website, so that should probably be updated. :-)

**Comment by suriyagp** [comment]
how to resolve this issue ???

**Comment by josephlewis42** [comment]
I'm pretty sure that the F12 part is actually a feature, not a bug. It keeps visitors from getting the tour *every* time they visit a page.

If you try it in private browsing mode it should show up every time. That being said, you can add an if statement to fix it:

    // Initialize the tour
    tour.init();

    // Start the tour
    tour.start();

    if (tour.ended()) {
      // decide what to do
      tour.restart();
    }

**Comment by suriyagp** [comment]
tour doesnt get start onclik even it is initialized before

**Comment by VirtualLegend** [comment]
Try to set true inside the start function:
Tour.start(true);

Op 21-jan.-2015 08:50 schreef Suriya Prakash <notifications@github.com>:
tour doesnt get start onclik even it is initialized before

---
