### ISSUE TITLE
The latest bootstrap tour cannot work with bootstrap 3.3.1

### ISSUE THREAD

**Issue by acesobee** [sorich87/bootstrap-tour#356]
My bootstrap tour script cannot work on bootstrap 3.3.1
In order to run the code, I need to run on bootstrap 3.1.1
Anyone can help on this ?

**Comment by jcorreia** [comment]
Hi,
thanks..this worked, but the text of the tab disapears..because the background is all white. any solution for this ?

**Comment by NephelimDK** [comment]
Hi,
i'm not sure if it's just me, but the line number is 511, not 513 as suggested.
Fixed the problem BTW
Thanks

**Comment by jbarbede** [comment]
This bug doesn't occur with the Boostrap current version 3.3.2. It seems Bootstrap team reverted some changes on Popover plugin between 3.3.1 and 3.3.2: 
* https://github.com/twbs/bootstrap/blob/v3.2.0/js/popover.js#L94
* https://github.com/twbs/bootstrap/blob/v3.3.1/js/popover.js#L94
* https://github.com/twbs/bootstrap/blob/v3.3.2/js/popover.js#L94

**Comment by garethbowen** [comment]
Upgrading to Bootstrap 3.3.2 worked for me.

**Comment by tiwarimukesh** [comment]
> Hi, i'm not sure if it's just me, but the line number is 511, not 513 as suggested. Fixed the problem BTW Thanks

Can you mention the code line which you commented and fixed the issue?
