### ISSUE TITLE
Confirm end tour option

### ISSUE THREAD

**Issue by ngocphamm** [sorich87/bootstrap-tour#358]
I just found this tool very useful on my current project. Thank you guys for all the hard work!!!

I just wan to add a confirmation box for the "End Tour" button so I won't accidentally click it and not see the tour appears anymore (I use LocalStorage). However, the end tour function seems to always be triggered no matter the answer for the confirm box is. LocalStorage always get written with `tour_end = yes`.

Anyone have the idea please tell me a solution for this. Thank you very much!!!

**Comment by sorich87** [comment]
Just stop propagation of the click event.
