### ISSUE TITLE
Question: Can you link a form button to the tour next button?

### ISSUE THREAD

**Issue by danialwestmorland** [sorich87/bootstrap-tour#359]
I have set up the bootstrap tour framework on my website which works great. 

At the moment I have 2 pages which the tour needs to traverse. On page one the last step you need to submit the form which saves the information and takes you to page 2. 

Is there a way to submit the form when user click next on the tour and incremented the step by 1 if the user clicks the submit button on the page.

I hope this makes sense.

**Comment by sorich87** [comment]
You'll need to write your own JavaScript code using `tour.next()` to go to next step after submit.

**Comment by danialwestmorland** [comment]
Thanks this wast the same solution I went for.
