### ISSUE TITLE
jQuery UI breaks bootstrap-tour

### ISSUE THREAD

**Issue by pdoggi** [sorich87/bootstrap-tour#370]
I'm currently using [jQuery UI 1.8.21](http://jqueryui.com/resources/download/jquery-ui-1.8.21.zip) and it breaks bootstrap-tour, so I can't use them together on the same page.  

My version of jQuery UI is older, so maybe there's a newer version of jQuery UI that works with bootstrap-tour.  Which would this be?

**Comment by sorich87** [comment]
What's the issue?

**Comment by pdoggi** [comment]
Sorry, I should have been more specific. What happens is the tour is pegged
at the top left corner of the page and doesn't anchor with the elements you
want to highlight. I suspect that it's a conflict with jQuery  UI's
popover or something.

I can send a screenshot later if you need it.

Right now, I'm just not using the two libraries together on the same page,
but thought I'd report the incompatibility since jQuery UI is quite
popular.

Let me know if I can help!

Thanks!

**Comment by gabrie30** [comment]
Any solutions for this one? I think I'm running into this issue as well.

**Comment by mnewmedia** [comment]
Also having a issue, that this and ionic use the same classname `popover`.

**Comment by elsurudo** [comment]
Me too (I think). Any workarounds?

**Comment by sorich87** [comment]
If it's an incompatibility of class names, there's not much we can do. You can set your own popover template using the `template` option when initialising the tour. So you can use a jQuery UI popover template e.g.
