### ISSUE TITLE
New bootstrap popover does not rerender template

### ISSUE THREAD

**Issue by alexortiz201** [sorich87/bootstrap-tour#374]
popover.js line 84 
 // POPOVER PLUGIN DEFINITION
  // =========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.popover')
      var options = typeof option == 'object' && option

      if (!data && option == 'destroy') return
      if (!data) $this.data('bs.popover', (data = new Popover(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

I had this working updated bs to newest version and the tours js increments correctly and render correct templates but seems to skip the rerendering of the popover's content.

 if (!data) $this.data('bs.popover', (data = new Popover(this, options))) if I force this new instance it does work.

Mind you, I'm not entirely sure this is the direct cause of tours not rerendering the template

**Comment by muschottkey** [comment]
Same Issue here..

**Comment by alexortiz201** [comment]
Figured it out orphans need a parent element to re render now just give it the .popover.tour class
