### ISSUE TITLE
New problem resulting from #167

### ISSUE THREAD

**Issue by watou** [sorich87/bootstrap-tour#375]
On a jammed up iPad, I get:

[Error] TypeError: 'undefined' is not a function (evaluating 'this.debug("LocalStorage quota exceeded. State storage failed.")')
	_setState (bootstrap-tour.min.js, line 22)
	setCurrentStep (bootstrap-tour.min.js, line 22)
	(anonymous function) (bootstrap-tour.min.js, line 22)
	_callOnPromiseDone (bootstrap-tour.min.js, line 22)
	showStep (bootstrap-tour.min.js, line 22)
	_callOnPromiseDone (bootstrap-tour.min.js, line 22)
	start (bootstrap-tour.min.js, line 22)
	startTour (supplier-portal.html, line 800)
	(anonymous function) (supplier-portal.html, line 652)
	c (jquery-1.10.2.min.js, line 4)
	fireWith (jquery-1.10.2.min.js, line 4)
	ready (jquery-1.10.2.min.js, line 4)
	q (jquery-1.10.2.min.js, line 4)

**Comment by sorich87** [comment]
It's fixed in v1.10.2 https://github.com/sorich87/bootstrap-tour/commit/3896bf727176660e80e026804b8e0bf061299f27

**Comment by watou** [comment]
Thanks; sorry I didn't keep up!
