### ISSUE TITLE
Cached popover's data property not cleared on calling destroy method

### ISSUE THREAD

**Issue by GeyseR** [sorich87/bootstrap-tour#378]
Whole webpage:
```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/bootstrap-tour/css/bootstrap-tour.min.css" />

</head>
<body>
    <script src="js/jquery-1.11.2.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
    <script src="bootstrap-tour/js/bootstrap-tour.js"></script>
    <script>
        $(function () {
            var tour = new Tour({
                storage: false,
                steps: [
                    {orphan: true, content: 'step1'},
                    {orphan: true, content: 'step2'}
                ]
            });
            tour.start();
        })
    </script>
</body>
</html>
```
For me on step two this tour still show "step 1" content. My investigation point me that bootstrap tooltip's hide method didn't call [complete](https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L298) inner function, that calling passed callback function, that should clear data attribute on body element.
But I don't know how to fix this :( 
Any toughts?

**Comment by mAmged** [comment]
same problem here

**Comment by wubenhe** [comment]
same problem as well. Is it any work around it?

**Comment by wubenhe** [comment]
So I don't know that is the work around or not. 
First, I use npm and webpack to load jquery and bootstrap-tour library. 
It is not working with multiple orphan. After I try to load the jquery and bootstrap-tour alone in the html and now it is working! I hope that could help.

**Comment by jordajm** [comment]
I was having the same issue. 
After spending some time debugging in bootstrap-tour, I decided it had to be a bootstrap bug and I rolled back to bootstrap V3.0.0 and it fixed the problem. Not sure why, but it works.

**Comment by reubenbrown** [comment]
Having the same problem as well. Tried rolling bootstrap back to v.3.0.0 but it didn't change anything. Could always hack it to set each step to a styled element so that it appears as if it's orphaned but that doesn't seem to be ideal.

**Comment by reubenbrown** [comment]
Having the same problem as well. Using bootstrap v.3.0.0 did not resolve the issue for me. 

My workaround was to set each step to the most parent element in the DOM. Then in my CSS I added these attributes to the `.tour` class from the template so that it would "look" like an orphaned element but still be able to update the title and content. 

```
.tour {
  top: 48.5px !important;
  left: 232.5px !important;
  display: block !important;
}
```

**Comment by fellmann** [comment]
I have committed a pull request to fix this problem by manually deleting the popover data from bootstrap after destroy.

**Comment by mastef** [comment]
Thank you @fellmann - was having same issue. Prev / Next buttons were useless and showing first orphaned step! Your PR fixed it for me

**Comment by sorich87** [comment]
Merged the fix.

**Comment by fellmann** [comment]
You can as well close https://github.com/sorich87/bootstrap-tour/issues/389
