### ISSUE TITLE
bootstrap tour within wont work without local admin rights

### ISSUE THREAD

**Issue by akhtaro** [sorich87/bootstrap-tour#383]
Hi.. New to this. Our users are unable to play the interactive tour of a website without local admin rights. We have Windows 7 x86 machines with IE8. I have checked and Active Scripting is enabled. Your help will be greatly appreciated. Thanks.

**Comment by sorich87** [comment]
I suspect it's something going on in your app. Does it happen with the demo at bootstraptour.com?

**Comment by sorich87** [comment]
Closed because of lack of response.
