### ISSUE TITLE
backdropPadding Question

### ISSUE THREAD

**Issue by noveweb** [sorich87/bootstrap-tour#388]
How to use backdropPadding for especific directions??? On the documentation show only to use for all directions. 

I have tried:
backdropPadding: "{top:30}"
backdropPadding: "{top=30}"
backdropPadding: "top:30"
backdropPadding: "top=30"

But only works:
backdropPadding: "30"

Thanks in advance and sorry by my bad english!!!

**Comment by btecu** [comment]
I think it's `backdropPadding: { top: 30}`, so no quotes.

**Comment by noveweb** [comment]
Btecu, error persists. Working only backdropPadding: "30".

**Comment by btecu** [comment]
Awesome. Feel free to close the issue.
