### ISSUE TITLE
Multiple orphaned steps not updating title/content properly.

### ISSUE THREAD

**Issue by 29thfloor** [sorich87/bootstrap-tour#389]
I have a tour where the first two steps aren't attached to an element. The first step loads fine, but then when I click next, it shows the content from the first step again.

If I continue through the tour and then click "Prev" to get back to the second step, it displays properly. If I click Prev again I still see the content from the second step.

So it seems like the first orphaned step loads properly in both directions, but from there it won't load any more steps properly until they are attached to an element.

Unfortunately this is in a local dev environment so I can't share a URL. 

Any idea what might be going on? I'm gonna try setting up a reduced test case to make sure it's not something else in our app causing a conflict.

**Comment by sorich87** [comment]
Same as #378

**Comment by jordajm** [comment]
I was having the same issue. I rolled back to bootstrap V3.0.0 and it fixed the problem. Not sure why.

**Comment by sorich87** [comment]
Fixed

**Comment by tylerecouture** [comment]
Is this included in your latest version?  I'm having this issue right now.

**Comment by caba8685** [comment]
I'm still having the same issue.
