### ISSUE TITLE
Get first elem with class

### ISSUE THREAD

**Issue by WilliamHua** [sorich87/bootstrap-tour#390]
I am trying to start the tour on an element which has no identifier but has many classes. There will be many elements with this class. How can I tell the tour.js to use the first element that it finds with this class?

Ex:
```
<div class="unit"></div> <!-- I want this div class to be selected by the tour -->
<div class="unit"></div>
<div class="unit"></div>

**Comment by sorich87** [comment]
Use jQuery :first selector https://api.jquery.com/first-selector/
