### ISSUE TITLE
Is there a way to prevent going to the next step on a condition?

### ISSUE THREAD

**Issue by random82** [sorich87/bootstrap-tour#391]
I'm looking for user action assertion. I would like to prevent a tour from advancing to the next step till a condition is fulfilled. I've tried returning promise function in tour.onNext but if my function returns false, the whole tour stops (it reacts on <- key and goes to the previous step though).

**Comment by ramatevish** [comment]
Have you tried forcing a re-start: `tourName.restart(true)`? It should continue where you left off. I've used it before for similar purposes, though I outright stopped the tour on the onShow callback.

**Comment by andrenm** [comment]
Still dont know how to do this

**Comment by matbeard** [comment]
Bump!

**Comment by gsoumya** [comment]
Now I facing Same issue, OnNext() I want to hadle next steps based on condition, but it executing immediate next step defined in the code
