### ISSUE TITLE
Infinite looping of each step

### ISSUE THREAD

**Issue by castledoor** [sorich87/bootstrap-tour#394]
I am using the tour the standalone version on a wordpress site, everything is running, but when the start the tour it just loops each step, .. and there are no errors in the console. 

This is all the code I have:

```
var tour = new Tour({
          debug: true,
         storage: false,
          steps: [
            {
              orphan: true,
              title: "DTC ZERO TOUR",
              content: "This tour will show you where important information is, so you never miss a thing!",
            },
            {
               orphan: true,
              title: "DTC ZERO TOUR",
              content: "Second thing!",
             }
          ]
        });

    tour.init(true);
    tour.start(true);
```

anyone else run into this issue?

**Comment by ramatevish** [comment]
I can't reproduce this with the lastest version. Can you take a look at https://jsfiddle.net/fbg5rk4v/ and let me know if it's working as you described?

**Comment by ramatevish** [comment]
Hey @castledoor - can you take a look at http://jsfiddle.net/fbg5rk4v/ and let me know if it's as you described? I can't seem to repro this.

**Comment by aaron1319** [comment]
I see this issue as well.  It looks like the tour is progressing to the next step but the title and content are not being updated, so it looks exactly like the previous step.  Happens only for orphan steps.

**Comment by castledoor** [comment]
?
