### ISSUE TITLE
Step with backdrop true and button element

### ISSUE THREAD

**Issue by ncampuzano** [sorich87/bootstrap-tour#398]
Hi, 

In a step of my Tour, I have a button with btn-primary class of Bootstrap, but when I apply the backdrop property the result is next:
![image](https://cloud.githubusercontent.com/assets/5368137/7139416/d79dbc9c-e28b-11e4-99d2-cde30c311c61.png)

How to make the Highlight doesn't affect the style button?

When hover button, this appear, but Only with hover button.
![image](https://cloud.githubusercontent.com/assets/5368137/7139441/0e43456e-e28c-11e4-9a9a-a56d82236d18.png)

**Comment by chrisvidal** [comment]
Hi,
yup i got the same issue, every time i enable the backdrop, the element is hidden behind a white panel instead of being highlighted

**Comment by sorich87** [comment]
It's a z-index issue. The backdrop container option https://github.com/sorich87/bootstrap-tour/pull/335 has been recently added to allow you to adjust the position of the backdrop in the DOM. It's not released yet but you can pull from the master branch.
