### ISSUE TITLE
Facing Issue with the Tour elements position

### ISSUE THREAD

**Issue by DivyaXapTech** [sorich87/bootstrap-tour#409]
Hi Sorich,

I am trying to use the bootstrap tour. I am facing issue with the tour elements position even though it is absolute it get stick to the window and also one more issue I am bothering right now. If I click Prev or Next then automatically I should be navigated to the div positions and show the tour element right but it does not show for me right now.

I have included 

```
<link href="bootstrap.min.css" rel="stylesheet">
<link href="bootstrap-tour.min.css" rel="stylesheet">
<script src="bootstrap.min.js"></script>
<script src="bootstrap-tour.min.js"></script>
```

 in my code as I am using Bootstrap framework already.

Looking forward for the reply

Thanks
Divya

**Comment by sorich87** [comment]
Please can you show a demo of the issue?
