### ISSUE TITLE
Ho do I end all the tours except the present tour from inside onclick button event

### ISSUE THREAD

**Issue by DivyaXapTech** [sorich87/bootstrap-tour#410]
Hi,

I have multiple tours in one js file. I want to execute only one at a time on different button clicks.

But when I try to execute any of teh tours all the other tours also executing. I didnt add start methods to them outside the code respective start methods are inside the button click events. Only init method is in global scope. Is that what casuing issue for me ?
 If I try to include init inside a button click function the tour is not at all running even though I add restart method.

Thanks

**Comment by sorich87** [comment]
Please can you show a demo of the issue?
