### ISSUE TITLE
Update backdrop on window resize

### ISSUE THREAD

**Issue by jeroenv** [sorich87/bootstrap-tour#413]
Backdrop doesn't get updated when window gets resized.

My solution for bootstrap-tour.js:
Update line 727:
if(this.backdrop.remove) this.backdrop.remove();

Add to line 319:
_this._hideBackdrop();

**Comment by sorich87** [comment]
Pull request? ;)

**Comment by gmircea** [comment]
I've tested this and it works. What's the status ?

**Comment by sorich87** [comment]
@gmircea If anyone submits a pull request, I'll merge it.

**Comment by gmircea** [comment]
Ok, I'll try to modify and then make a pull request but I'll need some help
regarding the workflow: I must update the two js files from the build/js
folder, and then minify them. So all four js files are up to date .
How to minify the js ? Is there some preferred  tool to use ?
Thanks

**Comment by sorich87** [comment]
Fixed in #454

**Comment by incorelabs** [comment]
I'm still fixing the issue where the white background size is not recalculated. I'm using v0.10.2. 

Normal Screen:
![screen shot 2015-12-01 at 12 36 21 pm](https://cloud.githubusercontent.com/assets/1456419/11494421/41980434-9828-11e5-90e3-93a03dfc7a84.png)

Resized Screen (Small to Big):
![screen shot 2015-12-01 at 12 34 36 pm](https://cloud.githubusercontent.com/assets/1456419/11494422/419a70fc-9828-11e5-872e-839a98eced0f.png)

Resized Screen (Big to Small):
![screen shot 2015-12-01 at 12 36 42 pm](https://cloud.githubusercontent.com/assets/1456419/11494420/4196eaf4-9828-11e5-9bc2-aaae146aa8c5.png)

var tour = new Tour({
		steps: [
			{
				element: ".a-css-filter",
				backdrop: true,
				title: "Some text",
				content: "Some text"
			}
		],
		template: "<div class='popover tour'><div class='arrow'></div><h3 class='popover-title'></h3><div class='popover-content'></div></div>"
	});

// Initialize the tour
tour.init();

// Start the tour
tour.start();
