### ISSUE TITLE
Tour restarts at various steps in FF and Chrome - OK in IE

### ISSUE THREAD

**Issue by Claes67** [sorich87/bootstrap-tour#420]
Hi,
are there any known issues between Firefox and IE? I am creating a multipage tour with approx. 35 steps, extra highligting (onShow). Works great in IE9 but restarts from step 1 every now and then in Firefox and Chrome. An excerpt of the code below: Sorry for the extremely bad markup... Thanks!!

<addr>
$(document).ready(function(){
	var demo1 = new Tour({
		name: "demo1",
		basePath: "/se/",
		backdrop: true,
		//debug: true,
		onEnd: function (demo1) {
			location.href = "/se/in/x.in.index.php";
		},
		template: "<div class='popover tour'><div class='arrow'></div><h3 class='popover-title'></h3><div class='popover-content'></div><div class='popover-navigation'><button class='btn btn-default' data-role='prev'>« Tillbaka</button> <button class='btn btn-default' data-role='next'>Nästa »</button> <button class='btn btn-default' data-role='end'>Avsluta</button></div></div>",
		steps: [{path: 'in/x.in.pe.whatis.php?demo=1', element: '#img_in_pe_intro_spflow', placement: 'right', onShow: function (demo1) { $('div#x-in-pe-whatis_models').show(); $('#img_in_pe_intro_projorg').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});$('#demoNavContent').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});}, onShown: function (demo1) { $('.popover-title').append('<span style=\'padding-left:15px; font-size:11px;\'>('+(demo1.getCurrentStep()+1)+' av 34)</span>'); }, title: 'Modeller', content: '<p>Inom XYZ:s metodik används modeller för uppdragets, projektets, programmets och projektportföljens livscykel och organisation.</p>'},
		{path: 'in/x.in.pe.key.php?demo=1', element: '#page_title', placement: 'bottom', onShow: function (demo1) { $('#demoNavKey').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});}, onShown: function (demo1) { $('.popover-title').append('<span style=\'padding-left:15px; font-size:11px;\'>('+(demo1.getCurrentStep()+1)+' av 34)</span>'); }, title: 'Färger', content: '<p>XYZ bygger på symboler och färger. Alla bilder och symboler i XYZ har färger som följer en färgkod där följande färger används:</p><p class=\'demotourBullet\'>Rött står för styrning och för organisationens långsiktiga affärsmål</p><p class=\'demotourBullet\'>Blått står för ledning</p><p class=\'demotourBullet\'>Gult står för operativt arbete och ansvar</p><p class=\'demotourBullet\'>Grönt står för slutresultat</p>'},
		{path: 'in/x.in.pe.key.php?demo=1', element: '#img_in_pe_key_symbols', placement: 'bottom', onShow: function (demo1) { $('div#x-in-pe-key_symbols').show(); $('#demoNavKey').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});$('#in').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});}, onShown: function (demo1) { $('.popover-title').append('<span style=\'padding-left:15px; font-size:11px;\'>('+(demo1.getCurrentStep()+1)+' av 34)</span>'); }, title: 'Symboler', content: '<p>I XYZ används symboler på ett konsekvent sätt för att förstärka och tydliggöra informationen i metodiken.</p>'},
		{path: 'in/x.in.pe.training.php?demo=1', element: '#demoNavTraining', placement: 'bottom', onShow: function (demo1) { $('#in').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});}, onShown: function (demo1) { $('.popover-title').append('<span style=\'padding-left:15px; font-size:11px;\'>('+(demo1.getCurrentStep()+1)+' av 34)</span>'); }, title: 'Utbildning', content: '<p>Under denna rubrik finner du en E-learning som på ett översiktligt sätt beskriver XYZ samt information om lärarledda kurser.</p>'},
		:
		:
		{path: 'ag/x.ag.index.php?demo=1', element: '#img_ag_index_intro', placement: 'bottom', onShow: function (demo1) { $('#ag').css({'z-index':'1102', 'background':'#fff', 'position':'relative'});}, onShown: function (demo1) { $('.popover-title').append('<span style=\'padding-left:15px; font-size:11px;\'>('+(demo1.getCurrentStep()+1)+' av 34)</span>'); }, title: 'Huvudflikar i XLPM', content: '<p>Under fliken Agilt beskrivs Scrum som är en agil metod. XYZ i agila projekt är en anpassning för att XYZ ska fungera optimalt i agila projekt. Scrum i XYZ kan tillämpas på alla typer av projekt som passar att tillämpas i en agil arbetsform.</p>'}]
		});
		demo1.init();
		demo1.restart();
});

**Comment by sorich87** [comment]
The `demo1.restart();` will restart the tour from step 1. Do `demo1.start();` instead.
