### ISSUE TITLE
step position

### ISSUE THREAD

**Issue by seesoe** [sorich87/bootstrap-tour#424]
how can i fine tune the position of a step? for example i have one step position set to right, but it is on a heigh menu so its default right position is middle but i want it towards the top. another example, i have a step positioned on the top of 3 tabs, one step per tab. but fthe first step the step is pointing on the middle tab. i want to position it all the way to the left to be above the first tab...

**Comment by sorich87** [comment]
One way I can think of would be to use CSS to customise

**Comment by seesoe** [comment]
ya i was having trouble with that so i was looking for a more native way.

**Comment by sorich87** [comment]
Sadly there isn't any native way.
