### ISSUE TITLE
existing tooltips/popover on the page spoil the Tour

### ISSUE THREAD

**Issue by alex29ua** [sorich87/bootstrap-tour#425]
Hi!
I have some BS popovers triggered by "hover" events on the page. Can't set up the tour, since it just disappears along with my existing popovers. For example, I start the tour, and then mouse moves above some element that triggers the popup. When mouse moves out, that popup disappears, but it also kills the tour as well.

Is there a workaround or fix for this?

**Comment by jsmits21** [comment]
I wouldn't say this is a bug exactly. What you could do is use the plugins callbacks to disable other popovers on the page, maybe something as simple as adding a class to them on tour start and removing the class on tour done.
