### ISSUE TITLE
Nothing WORKS! Zero support!

### ISSUE THREAD

**Issue by UXengineer** [sorich87/bootstrap-tour#427]
You've deleted my feedback from yesterday, so I just wanted to let you know I have spent over 8 hours trying to get this CRAP to work, but I gave up!

Documentation leaves a lot to wish for, and the examples are even worse!

**Comment by ramatevish** [comment]
![](http://www.quickmeme.com/img/63/63c3fdd19dec45767470b46447f9a4fdd5223e220f694eb465b8d9a8ad79c5d7.jpg)

If you want help with something, you generally explain your problem ("it doesn't work" isn't an explanation), and politely ask for assistance. Opening an issue without an explanation, full of insults aimed at the maintainer and the project merits the 4 character response @sorich87 gave you yesterday.
