### ISSUE TITLE
[BUG] [QUESTION] Bootstrap Tour Ended - Init Prevented

### ISSUE THREAD

**Issue by hiraq** [sorich87/bootstrap-tour#429]
I have enable debug in my page, when i see at console, it thrown a message:

> Bootstrap Tour 'tour' | Tour ended, init prevented.

What happened here ? Because suddenly all tour steps not showed now

**Comment by sorich87** [comment]
What happened is you ended the tour in the past. When the tour has been ended once, it doesn't start again on subsequent page loads.

You can force it to continue using `tour.start(true)` or restart it using `tour.restart()`.
