### ISSUE TITLE
Tour with Bootstrap-modal (http://jschr.github.io/bootstrap-modal/)

### ISSUE THREAD

**Issue by LeonardHarley** [sorich87/bootstrap-tour#441]
Firstly, GREAT PRODUCT, truly awesome tour application!

I'm having a problem that is beyond my pay-grade / abilities and am hoping someone can assist me, although it's not actually a problem with the tour code as far as I can tell. Yeah, yeah "then why the hell are you logging an issue here" - I know, but since this is going to happen to others and impacts on the useability of this solution I feel OK to ask for guidance here. I guess it's always an issue when there's compatibility issues between 2 components from different sources....

OK - so I'm using this Bootstrap-modal solution (http://jschr.github.io/bootstrap-modal/). I have a tour setup that starts off on the main canvas and all is perfectly fine. The issue I'm having is that at a particular point in the tour I'd like to open a modal and provide tour info relating to same. When I fire the modal it's simply removing the divs created by the tour completely.... (!@#& WTF?)

At 1st I thought it may be a z-index / stacking / opacity issue but for sure it's not - watching the HTML in Firebug confirmed that as soon as the modal show is fired it's completely removing the tour divs appended to the body when tour.start() fires.

I fully understand it's a cross component compatibility issue and it's not the tour code that's causing the problem but I'm really flummoxed by this one. Any ideas would be greatly appreciated. 

Many thanks in advance...

Len
PS - am going to post similar on the jschr side and hopefully there will be co-operation / collaboration by folks far more skilled than me to solve this one....

**Comment by sorich87** [comment]
I would suggest ending the tour before the modal is opened then starting it again when the modal is closed so that it adds back the elements removed by the modal.

**Comment by LeonardHarley** [comment]
Thanks for the prompt reply. The issue seems to be related to timing / execution context - the tour does actually attach itself correctly to a modal popup (apart from having to adjust it's z-index's) if the modal is called/drawn and the the tour is then instantiated. However if the modal is an element being referenced as a step once the tour has started the tour check executed by _isOrphan cannot find the element yet as it's not drawn.

I've tried ending the tour by calling a custom check function in the onNext of the previous tour step but the next step with the modal element in the step chain still executes (at which point _isOrphan is true due to modal not having been drawn yet). 

I'm relatively new to JS development so struggling to follow the execution context of the Tour code - I'm pretty sure that if there was a way somewhere to check if the next element had a class of "modal" and if so then wait for the completion of the modal drawn event ('shown.bs.modal') and only then continue with the Tour that it would attach itself to the modal correctly.

**Comment by LeonardHarley** [comment]
I've managed to solve most of the issues for my specific implementation; admittedly it's a hack job, not everything works 100% as it should I guess, but hey it works for what I need, so I'm happy. Posting what I've done here in case it helps someone or possibly assists with ideas for future enhancements...

**CSS changes**
Due to custom Bootstrap 3 CSS adjusted the z-index of `.tour-backdrop` and `.tour-step-background` to *1055*, and `.tour-step-backdrop` and `.tour-step-backdrop > td` to *1056*.

**Tour object extension**
Created the following object 
```javascript
var modalSteps = {
     screens: [
           { modal: '#modal_ID', field: '#modal_ID' }, //if wanting to have a step discussing the modal as a whole
           { modal: '#modal_ID', field: '#test_id_for_tour1' }, //elements on modal being targeted
           { modal: '#modal_ID', field: '#test_id_for_tour2' },
           { modal: '#modal_ID', field: '#test_id_for_tour3' }
      ]
};
``` 
and added to tour object prior to initialization
```javascript
var tour = new Tour({
//as normal however make sure that the following is set in addition to anything else when ending the tour
onEnd: function (tour) {
       $("[data-dismiss=modal]").trigger({ type: "click" });
       $($body).removeClass('modal-backdrop');
    },
});
tour.modalSteps = modalSteps;
``` 
**Changes to bootstrap-tour.js**
In `showStepHelper`,
```javascript
current_path = [document.location.pathname, document.location.hash].join('');
          if (_this._isRedirect(path, current_path)) {
            _this._redirect(step, path);
            return;
          }
/*----------------------------*/
 INSERT CODE HERE 
/*----------------------------*/
if (_this._isOrphan(step)) {
            if (!step.orphan) {
              _this._debug("Skip the orphan step " + (_this._current + 1) + ".\nOrphan option is false and the element does not exist or is hidden.");
```
 added the following:
```javascript
if ( _.pluck(_.filter(_this.modalSteps.screens, 'field', step.element.toString()), 'modal').length > 0 ) {
       $(_.pluck(_.filter(_this.modalSteps.screens, 'field', step.element.toString()), 'modal')[0]).removeClass('fade');
       $(_.pluck(_.filter(_this.modalSteps.screens, 'field', step.element.toString()), 'modal')[0]).modal('show');
} else {
       $("[data-dismiss=modal]").trigger({ type: "click" });
       $($body).removeClass('modal-backdrop');
}
```
Note: lodash required (https://lodash.com/)

In `Tour.prototype._showBackdrop`,
```javascript
this.backdrop.backgroundShown = true;
/*----------------------------*/
 INSERT CODE HERE 
/*----------------------------*/
return $('body').append(this.backdrop); //Note repositioning of this line
```
added the following:
```javascript
if ( _.pluck(_.filter(this.modalSteps.screens, 'field', this._options.steps[this._current].element.toString()), 'modal').length > 0 ) {
     return $(_.pluck(_.filter(this.modalSteps.screens, 'field', this._options.steps[this._current].element.toString()), 'modal')[0]).append(this.backdrop);
} else {
     return $('body').append(this.backdrop);
}
```
In `Tour.prototype._showOverlayElement`,
```javascript
elementData = {
   width: $element.innerWidth(),
   height: $element.innerHeight(),
   offset: $element.offset()
};
/*----------------------------*/
 INSERT CODE HERE 
/*----------------------------*/
this.backdrop.$background.appendTo('body'); //Note repositioning of this line
if (step.backdropPadding) {
   elementData = this._applyBackdropPadding(step.backdropPadding, elementData);
}
```
added the following:
```javascript
if ( _.pluck(_.filter(this.modalSteps.screens, 'field', this._options.steps[this._current].element.toString()), 'modal').length > 0 ) {
    this.backdrop.$background.appendTo($(_.pluck(_.filter(this.modalSteps.screens, 'field', this._options.steps[this._current].element.toString()), 'modal')[0]));
} else {
    this.backdrop.$background.appendTo('body');
}
```
