### ISSUE TITLE
Control outside of the popover

### ISSUE THREAD

**Issue by DemarsM** [sorich87/bootstrap-tour#442]
I would like to leave the navigation control outside of the popover in a fixed div or in draggable modal panel.

Is anybody have an idea how it could be done?

**Comment by sorich87** [comment]
You can build it yourself with your own html/css code and the methods `prev()`, `next()`, `end()`. See the documentation for the available methods list http://bootstraptour.com/api/.

**Comment by DemarsM** [comment]
Thank you, I did it. I thought to create a branch is someone could be intetested
