### ISSUE TITLE
tour onShown() vs step onShown();

### ISSUE THREAD

**Issue by DemarsM** [sorich87/bootstrap-tour#443]
Is it wanted that if I have `onShown()` function defined in the tour and another `onShown()` function defined in the step, only the function defined in the step will be triggered not both?  I suppose this is the same for other `onSomething()` options?

I was hoping that a general `onShown()` function at the tour level could be triggered for every steps even when a more specific `onShown()` function is defined at the step level.

**Comment by sorich87** [comment]
Yes, only the function defined in the step will be triggered. And it's the same for all the `onSomething()` options.

You can just call your general `onShown()` function from the specific one.
