### ISSUE TITLE
Popovers are not opening...

### ISSUE THREAD

**Issue by bgetting** [sorich87/bootstrap-tour#444]
I'm able to initialize a tour, and once started the window will scroll to the correct position, but the popover will not open. I keep getting this error from bootstrap.js:

    [Error] TypeError: undefined is not a function (evaluating 'data[option]()')
    (anonymous function) (bootstrap.js, line 1810)
    each (jquery-1.11.1.min.js, line 3)
    each (jquery-1.11.1.min.js, line 3)
    Plugin (bootstrap.js, line 1797)
    _showPopover (bootstrap-tour.js, line 513)
    showPopoverAndOverlay (bootstrap-tour.js, line 329)
    (anonymous function) (bootstrap-tour.js, line 611)
    complete (jquery-1.11.1.min.js, line 5)
    j (jquery-1.11.1.min.js, line 3)
    fireWith (jquery-1.11.1.min.js, line 3)
    i (jquery-1.11.1.min.js, line 5)
    tick (jquery-1.11.1.min.js, line 5)

Any ideas? I'm using Bootstrap 3.3.1 and Jquery 1.11.1. Thanks for any help with getting this working, it seems like a great tool.

**Comment by bgetting** [comment]
It appears that BootstrapTour is not compatible with the JS from Bootstrap 3.3.1.

**Comment by sorich87** [comment]
Yes. Please use 3.3.2 or a more recent version.

**Comment by hrishikeshchoudhari** [comment]
Marking for re-opening this please.

I upgraded my Bootstrap from v.3.3.1 to v.3.3.2 and am still facing this issue:
`Error: Uncaught TypeError: $element.popover is not a function (http://localhost:8080/bower_components/bootstrap-tour/build/js/bootstrap-tour.js:502)`
