### ISSUE TITLE
Steps linger when modal is closed

### ISSUE THREAD

**Issue by kinato** [sorich87/bootstrap-tour#445]
I am using a a Bootstrap modal and I have steps telling the user how to use the modal dialog. When the modal dialog is closed or dismissed (by clicking outside the modal) the step lingers and the buttons no longer work.

**Comment by sorich87** [comment]
Please can we have a demo?

**Comment by kinato** [comment]
Unfortunately I can't, as it's deployed to SP. Is there anything else I can provide?

I've just tried dumping the tour object to the console and the only difference I can find is that when the tour is going (and the modal is displayed) _inited is set to true. After the modal is dismissed the tour object reports _inited as false.

**Comment by kinato** [comment]
This was my bad. It was a scoping issue as I was using a number of controllers and when I wanted the tour to end, it had been disposed.
