### ISSUE TITLE
drop down

### ISSUE THREAD

**Issue by webdvlpr** [sorich87/bootstrap-tour#449]
(Not an issue) Sorry, noob question. Is there an option to choose an element contained in a drop down menu?

**Comment by ramatevish** [comment]
You can choose just about anything with a css selector. However, you'd want to attach an onShow handler to the dropdown step that emulates a hovering over it so that the step appears correctly.

**Comment by webdvlpr** [comment]
Thanks! Here's what I did for anyone Googling this:

onShow: function(tour) { $("#selector").show();}
