### ISSUE TITLE
Dropdown menu prolem

### ISSUE THREAD

**Issue by cobyl** [sorich87/bootstrap-tour#463]
Problem with twitter bootstrap 2.3.1 and dropdown menu opening:

I open drop down menu using onShow method from boostraptour.addStep  but dialog is shown as orphan, not close to element.

+ (question) 
Can i preserve dropdown menu open status between steps? (twitter bootstrap 2.3.1)

**Comment by asharma-r7** [comment]
+1

**Comment by sorich87** [comment]
Duplicate of #276
