### ISSUE TITLE
Bootstrap-tour  with Requirejs

### ISSUE THREAD

**Issue by asharma-r7** [sorich87/bootstrap-tour#464]
This isn't playing nicely with requirejs. Below is a taste of my requirejs config. As you can see, I have added "jquery" as a dependency as I am getting "Uncaught ReferenceError: jQuery is not defined". 

I am seeing bootstrap-tour.min being pulled it but it is chucking out the error mentioned above and this is due to jQuery being incorrectly injected.

paths: {
    .....
   "bootstrap-tour": "../bower_components/bootstrap-tour/build/js/bootstrap-tour.min"
}
shim: {
   "bootstrap-tour": {
       deps: ["jquery"] // Yes, I am requiring jQuery correctly. 
   }
}

Any help is appreciated.

**Comment by nsp** [comment]
+1

**Comment by asharma-r7** [comment]
So this is what my shim looks like in order to get this working.

"bootstrap-tour": {
        deps: ["jquery"],
        init: function() {
           return this.Tour;
        }
     }

Within the init method 'this' refers to the window object. Isn't the most eloquent fix, but it works for the mean time.

I would appreciate any feeback for a better solution.

**Comment by hrishikeshchoudhari** [comment]
The workaround provided by @asharma-r7 worked for me. 

That, and writing `var Tour = require("bootstrap-tour");` in the Angular controller.

**Comment by DemersM** [comment]
This is my settings and it works:

```
require.config({
    baseUrl: "./scripts",
    paths: {
        jquery: "jquery-2.1.4.min",
        bootstrap: "../lib/bootstrap/js/bootstrap.min",
        bootstrap_tour: "../lib/bootstrap/js/bootstrap-tour",
    },
    shim: {
        bootstrap: ['jquery'],
        bootstrap_tour: ['bootstrap'],
    },
    waitSeconds: 0
});

define(['jquery', 'bootstrap', 'bootstrap_tour'], function($, bootstrap, bootstrap_tour) {

});
```

**Comment by sorich87** [comment]
AMD and CommonJS support has been added 57ee74898b17754e1119c0dab75a1d1151e1dd2a.
