### ISSUE TITLE
How to end only one tour when multiple tours are running on a browser simultaneously

### ISSUE THREAD

**Issue by DivyaXapTech** [sorich87/bootstrap-tour#466]
Hi,

I have implemented multiple tour code. I have the anchor tags inside the tour content which will start another tours.

When multiple tours are running on the browser if I end one tour all other tours are stopping automatically. It am unable to go next steps in the remaining tours once I click on the end tour in one module.

How do I restrict the end tour to only present tour from which the end tour instruction has raised.

Look forward for your help and support.

Thanks & Regards

**Comment by brexis** [comment]
Hi @DivyaXapTech 
Can you show us your sample code?

**Comment by sorich87** [comment]
You have to set the tour name property

**Comment by aarontgrogg** [comment]
And setting a tour name is as simple as:
`var tour = new Tour({
  name: "tour",
  ...`
http://bootstraptour.com/api/
