### ISSUE TITLE
Add disabled="disabled" for last "next"

### ISSUE THREAD

**Issue by ronschi** [sorich87/bootstrap-tour#467]
You should add disabled="disabled" to the last step when a tour finishes. At the moment you're only using a disabled-styling.

Now:
`<button class="btn btn-sm btn-default disabled" data-role="next">Next »</button>`

Better:
`<button class="btn btn-sm btn-default disabled" data-role="next" disabled="disabled">Next »</button>`

Add:
`if (step.prev < 0) {
        $prev.addClass('disabled');
        $prev.prop('disabled', true);
      }`

`if (step.next < 0) {
        $next.addClass('disabled');
        $next.prop('disabled', true);
      }`

**Comment by ztane** [comment]
+1

**Comment by ztane** [comment]
Why this was closed? If it is unclear, the button is still clickable - and the event is fired, even though it is greyed out.

**Comment by ronschi** [comment]
Agree to ztane. Still an open issue.

**Comment by ousram** [comment]
I've submitted a pull-request for this.
