### ISSUE TITLE
v0.10.2 fails to install with npm

### ISSUE THREAD

**Issue by SpaceK33z** [sorich87/bootstrap-tour#468]
The current release, v0.10.2 fails to install with npm. This has been fixed a long time ago with 9136219ae346c3b40f26b7a005af573fac3deb37, but no new version with this fix has been released yet. Previously you could still install the package, but now that node v4 is released with a new version of npm, it fails to install completely without the fix in above commit.

Could you release a new version? Looking at the changes between [v0.10.2...master](https://github.com/sorich87/bootstrap-tour/compare/v0.10.2...master) there are enough other changes to justify a release.

**Comment by jaapz** [comment]
Looks like v0.10.2 has just not been pushed to npm yet. Could someone (@sorich87) push that version please?

**Comment by jaapz** [comment]
Actually, looks like I was wrong in my previous comment. 0.10.2 does not have the fixed package.json so it won't install.

**Comment by sorich87** [comment]
@ousram please can you create an npm account so that I can add you as a owner? https://docs.npmjs.com/cli/adduser

**Comment by ousram** [comment]
Done !
https://www.npmjs.com/~ousram

**Comment by sorich87** [comment]
I added you.

**Comment by timkendrick** [comment]
Hi guys – thanks for a great library! It'd be great to get v0.10.2 up on npm to enable the `backdropContainer` option – would you be able to publish a new version?

(Also I'm sure you're aware that the release tagged as 0.10.2 currently has the 0.10.1 files in the build folder, so something to bear in mind if you do manage to have a look at it...)

**Comment by chrisbenincasa** [comment]
I'm also trying to add 0.10.2 via NPM, but am unable to because of this issue.

**Comment by jaapz** [comment]
@sorich87 @ousram any news?

**Comment by sorich87** [comment]
@ousram please can you release 0.10.3?

**Comment by ousram** [comment]
I just released 0.10.3
If it's ok, I'm going to close this issue.

**Comment by btecu** [comment]
@ousram Can we get 0.10.3 on bower?
