### ISSUE TITLE
Adding steps in between the tour without affecting steps defined while creating tour

### ISSUE THREAD

**Issue by Ankita-Palekar** [sorich87/bootstrap-tour#473]
I have a tour with 4 steps  and once user reaches step 2 I need to take user input from drop down and depending upon the drop down value I need to take him to the step according to his choice else if user does not select anything from the drop down it will go according to the steps given while creating a tour. When user chooses drop down value one div with input box is shown and this div is hidden otherwise .So is there a way where in I can insert step in between  when user chooses drop down?because in my case it skips of all the remaining steps and goes to the last step if user chooses value from the drop down. Otherwise flow is smooth enough.

        $scope.walk_through = new Tour({  
            steps: [
              {
                element: "element1",
                orphan: true,
                title: "Template 1",
                content: "template 1 content ",
                placement: "bottom",
                template: $scope.get_template(),
                // backdropPadding: 10,
              },
              {
                element: element2,
                title: "this step shows drop down",
                content: "next step should show template related to the user chosen drop down value else it should go to the next step g",
                placement: "bottom",
                template: $scope.get_template()
              },
              {
                element: element3,
                title: "this step is seen ",
                content: "this step is seen after step 2 if user does not pick any value from the drop down else once user chosen step is shown this step will be shown",
                placement: "bottom",
                template: $scope.get_template(),
                
              } 
            ],
            backdrop: true,
            backdropContainer: 'body',
            backdropPadding: 0,
            debug: true
          }

          $scope.walk_through.init();
          $scope.walk_through.restart();

 on change of drop down I am adding one more step, need to involve add step is because element is hidden and is accessible only once user picks any value from the drop down, basically this is an in between step and if does not choose any user then it should go according to the steps defined above

        $scope.user_changed_dropdown = function(){
          add_rates_wt = angular.element('body'),find('.add-rates-wt:first-child'); // this particular element is hidden and available only once user chooses value from dropdown
          $scope.walk_through.addStep({
              element: element4,
              title: "in between step",
              content: "This step should be shown once user clicks on drop down and after this all remaining steps should be shown defined earlier",
              placement: "bottom",
              template: $scope.get_template()
            });
          $scope.walk_through.next()
        }

**Comment by desperate-man** [comment]
+1

**Comment by ousram** [comment]
What you should is this : 
1 - Create all the steps first
2 - Then, according to your user action, let him continue or take him to a specific step with the goTo(i) method.
