### ISSUE TITLE
Tour delay too unpredictable for AJAX

### ISSUE THREAD

**Issue by frank184** [sorich87/bootstrap-tour#476]
Our website uses bootstrap modals very heavily, our tours should explain the different parts of the app, however the modals are loaded using AJAX. 

Delays have become increasingly inconsistent during testing and I feel like actually getting the step to wait for jqXHR.done() is the best solution.

Is there a way to do this as is? I don't mind having to write this in, however I would like to know if anyone has faced this problem and how its been solved.

### EDIT

Okay, I got it working, but it feels wrong. If anyone is interested I'll make a fork.

I'm still open to suggestions!

**Comment by frank184** [comment]
Okay, I got it working, but it feels wrong. If anyone is interested I'll make a fork.

I'm still open to suggestions!

**Comment by sorich87** [comment]
You can pass a promise to the `onNext` callback. The tour will wait for it to be resolved before continuing to the next step.

**Comment by frank184** [comment]
Oh shoot, thank you! Sorry for wasting your time.

**Comment by alexvibealex** [comment]
Hi @sorich87 ,@frank184  can you guys please share an example for promise on onNext callback 
Actually some elements are adding dynamically with ajax and it is skipping steps for dynamically added elements and jumps to the last step .
I trying to do the same things with this code but its not working for me : 

`
course_pursue_object = new Tour({
name: "course_pursue",
 container: "body",
 keyboard: true,
steps:course_pursue,
onEnd: function (tour) {
//ajax call to save flag thet tour has ended
  end_tour_wplms("course_pursue");
},
onNext: function(tour){ 
	deferred.done(function(value) {
		alert(value);
	});

	tour._current = parseInt(tour._current);
	if(tour._current > tour._options.steps.length)
		return;
	var element2 = tour._options.steps[(tour._current+1)].element;
	if($("body").find(element2).length > 0){
		//promise return I guess
		return $("element").promise();
	}else{
		return false;
	}
},
});	`

**Comment by frank184** [comment]
Try returning the AJAX object to `onNext`.

```
onNext: function() {
  return $.get('some_dynamic_content', function(data) {
    # add content
  }).fail(function() {
    # maybe back up a step
  })
}
```
