### ISSUE TITLE
Release 10.2 package contains 10.1 code

### ISSUE THREAD

**Issue by wbsimms** [sorich87/bootstrap-tour#477]
I just noticed this. Release 10.2 package contains 10.1 code.

Also cdnjs doesn't have the 10.2 version.

Thanks!

**Comment by esoyke** [comment]
Noticed this today and had to manually copy the raw source, thought Bower was going haywire.

**Comment by patriotdev** [comment]
I noticed this too.  Can someone update version 0.10.2 with the correct build in Bower?

Thanks!

**Comment by admangum** [comment]
+1

**Comment by sorich87** [comment]
0.10.3 was released.

**Comment by admangum** [comment]
@sorich87: looks like 0.10.3 has the [same problem](https://github.com/sorich87/bootstrap-tour/blob/v0.10.3/build/js/bootstrap-tour.js)

**Comment by sorich87** [comment]
@admangum it's just the header that wasn't updated in the file.
