### ISSUE TITLE
Just doesn't seem to work. Not sure why.

### ISSUE THREAD

**Issue by ScottSpittle** [sorich87/bootstrap-tour#482]
Everything is loaded correctly, the config is set and init() / start() is fired, yet nothing happens...
Any ideas?

**Comment by frank184** [comment]
Try restart()?

**Comment by jstoeffler** [comment]
I also felt like this the first time, and there were two reasons:
- The tour had worked once, so it wasn't showing after that. You can use the "storage: false" option to show it every time the page is reloaded:

    var tour = new Tour({
      steps: [
         //...
      ],
         //...
      storage: false
    });

- The page wasn't fully rendered, so I've used a timeout to start it. I'll replace that later with some callback, but it made the tour work:

   setTimeout(function () {
      // Start the tour
      tour.start();
    }, 1000);

**Comment by ScottSpittle** [comment]
Thanks, I'll give this a try and get back to you.
