### ISSUE TITLE
Backdrop changes element's background colour

### ISSUE THREAD

**Issue by shaneparsons** [sorich87/bootstrap-tour#490]
Is there a way to disable the colour changing that happens to an element when `backdrop: true`?

The image below illustrates the problem I'm having.. the button colour is supposed to be `primary` i.e. `#337ab7`.

![screen shot 2015-11-16 at 3 34 55 pm](https://cloud.githubusercontent.com/assets/5495493/11194007/b78cbe30-8c77-11e5-899b-41848adcd5eb.png)

**Comment by steveostudios** [comment]
I'm having the same issue.

**Comment by ousram** [comment]
![screenshotissue](https://cloud.githubusercontent.com/assets/11911945/11470107/8a6fb4fe-975b-11e5-9b63-a7575bf011ed.png)
I don't hav this issue, maybe it's due to another problem in your code. Did you try with a new blank project ?

**Comment by shaneparsons** [comment]
Unfortunately I'm unable to play around with this further because I ended up using something else for my tour, but yes, the project was a blank project with only the bootstrap and bootstrap-tour files.

On Nov 30, 2015, at 6:12 AM, Rahmane OUSMAE <notifications@github.com<mailto:notifications@github.com>> wrote:


[screenshotissue]<https://cloud.githubusercontent.com/assets/11911945/11470107/8a6fb4fe-975b-11e5-9b63-a7575bf011ed.png>
I don't hav this issue, maybe it's due to another problem in your code. Did you try with a new blank project ?

-

**Comment by DaddyWarbucks** [comment]
I am having this same issue

**Comment by ousram** [comment]
please create a jsfiddle for this issue, so we could more understand (the problem), based on your code.

**Comment by tmckd** [comment]
I also had this problem.  For me, the solution was to make sure that in my application.css.sass file I import bootstrap-tour before I import bootstrap.

So before I had:
@import "bootstrap"
@import "bootstrap-tour"

and I had the problem.

Now I have:
@import "bootstrap-tour"
@import "bootstrap"

and the problem is gone.

**Comment by elivinskydb** [comment]
That may not be a good approach. I'd recommend wrapping the button in a div and use the wrapper to set the Step.

The background: inherit added to the element I think it is to better stick out the element for the Tour.

**Comment by gdelhumeau** [comment]
Hello.
I have reproduced this issue on a jsFiddle:
https://jsfiddle.net/Lz3d4vns/2/

With screenshots:
**Before:**
![before](https://cloud.githubusercontent.com/assets/1298947/12914147/fb9abfd0-cf22-11e5-86e8-15efa7946d86.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/1298947/12914146/fb9836e8-cf22-11e5-9251-4889d35366cc.png)

**Comment by gdelhumeau** [comment]
Thanks for having re-opened this issue.

The problem is that `.tour-step-background` has `background: inherit;`, which I guess means that it uses the `body` background.

In that case, the background of the element is dark but the body is light so we have this inappropriate result.

In my opinion, a fix is not easy. Adding `opacity: 0.5;` could help but only when the element has a dark background.

It would be interesting to see how the boostrap tour works with dark themes, like: http://bootswatch.com/cyborg/.

I hope it helps,

Thanks,
Guillaume

**Comment by elivinskydb** [comment]
As I suggested earlier, you could just wrap the element in a <div /> and use that as the step.

Your jsFiddle updated: https://jsfiddle.net/Lz3d4vns/3/

**Comment by gdelhumeau** [comment]
You mean in a div?

**Comment by gdelhumeau** [comment]
Then, it's easy to fix it directly in bootstrap-tour. Wrap the element with jQuery before displaying the step, and unwrap it after the step disappears.

It would not require the user to change the HTML of its page, and bootstrap-tour gets better!

**Comment by ousram** [comment]
What do you think about allow developer to set the step element background-color
Something like this :
 steps: [
  {
    element: "#startTour",
    title: "Title of my step",
    content: "Content of my step",
    placement: "bottom",
    backdrop: true,
    background-color : '#529abb'
  }
]

**Comment by gdelhumeau** [comment]
@ousram: I don't think it's a good solution. Sometimes you don't know what color you should use. In my example, you can replace the bootstrap CSS file by any bootswatch equivalent and it should continue to work without any modification in the JS.

**Comment by gdelhumeau** [comment]
To be more precise, I am a developer of [XWiki](http://www.xwiki.org/xwiki/bin/view/Main/WebHome). We have a [default skin](http://extensions.xwiki.org/xwiki/bin/view/Extension/Flamingo+Skin) but the user could use different [themes](http://extensions.xwiki.org/xwiki/bin/view/Extension/Flamingo+Theme+Application) (even from [bootswatch](http://extensions.xwiki.org/xwiki/bin/view/Extension/Bootswatch+Themes+for+Flamingo)).

I am currently working on an extension for XWiki called [Tour Application](http://extensions.xwiki.org/xwiki/bin/view/Extension/Tour+Application) that should work with every theme that the user can chose. So I need a generic solution.

I could probably add some code in my application to handle this use-case, but it would be a shame to not have it in the upstream library.

WDYT?

**Comment by ousram** [comment]
If setting the right color is too much, maybe the developer can set if yes or no, he wants the background-color to change.
I'm saying that because, the background:inherit property, is important although it sometimes falls to not so good results (buttons).

**Comment by ousram** [comment]
@sorich87 , what do you think ?

**Comment by sorich87** [comment]
@gdelhumeau

> Then, it's easy to fix it directly in bootstrap-tour. Wrap the element in a <div> with jQuery before displaying the step, and unwrap it after the step disappears.

Won't it break some designs? I'm think about when people use rules like `.some-selector > div` e.g. on the element where the popover is applied. Making Bootstrap Tour modify their HTML code to show the popover may break these cases.

**Comment by elivinskydb** [comment]
Also it could break some event binding. Why is it that hard to wrap it manually?

**Comment by sorich87** [comment]
@ousram about your solution of setting the background color, would setting the color automatically from the element color be a good solution?

**Comment by gdelhumeau** [comment]
@sorich87: Indeed. I should have thought more about the impact of this proposition.

@elivinskydb: We cannot always change the HTML code, especially from 3rd parties.

**Comment by gdelhumeau** [comment]
Other idea: stop having a unique `.tour-backdrop` div that cover all the page, but instead create 4 divs:
- one on top of the element to show
- one above
- one on the left
- one on the right

In that case, we don't need to play with the `z-index` attribute, nor the background color of the element. The result would be visually the same for the backdrop, but this bug would be fixed.

What do you think?

Thanks,

Guillaume

**Comment by sorich87** [comment]
@gdelhumeau good idea! working on it.

**Comment by sorich87** [comment]
A new way to handle backdrop has been implemented in 7f98180015f02231f5e9b9689785413fbe070454. Please test.

**Comment by gdelhumeau** [comment]
It seems it works:
https://jsfiddle.net/Lz3d4vns/21/

![screen](http://tof.canardpc.com/view/e1918743-fec6-44fe-9c50-b3e3b104f969.jpg)

**Comment by jonwilcox** [comment]
That's great. I was having the same problem. I downloaded that newer build and it worked great (although I don't think the minified versions in that build had the updates in them). Any idea when this will make it into an official release?

**Comment by linking2014** [comment]
with this solution, the highlight section won't have border-radius any more. I prefer to add a background-color option rather than handle backdrop with 4 divs.
