### ISSUE TITLE
Backdrop not adjusting to the size of the content

### ISSUE THREAD

**Issue by incorelabs** [sorich87/bootstrap-tour#494]
I'm still fixing the issue where the white background size is not recalculated. I'm using v0.10.2. 

Normal Screen:
![screen shot 2015-12-01 at 12 36 21 pm](https://cloud.githubusercontent.com/assets/1456419/11494421/41980434-9828-11e5-90e3-93a03dfc7a84.png)

Resized Screen (Small to Big):
![screen shot 2015-12-01 at 12 34 36 pm](https://cloud.githubusercontent.com/assets/1456419/11494422/419a70fc-9828-11e5-872e-839a98eced0f.png)

Resized Screen (Big to Small):
![screen shot 2015-12-01 at 12 36 42 pm](https://cloud.githubusercontent.com/assets/1456419/11494420/4196eaf4-9828-11e5-9bc2-aaae146aa8c5.png)

var tour = new Tour({
		steps: [
			{
				element: ".a-css-filter",
				backdrop: true,
				title: "Some text",
				content: "Some text"
			}
		],
		template: "<div class='popover tour'><div class='arrow'></div><h3 class='popover-title'></h3><div class='popover-content'></div></div>"
	});

// Initialize the tour
tour.init();

// Start the tour
tour.start();

**Comment by ousram** [comment]
Please, to understand more this issue a jsfiddle will be welcome.

**Comment by sorich87** [comment]
@ousram it happens when you create a tour with backdrop then you resize the window.

**Comment by incorelabs** [comment]
Yup.. when we resize the window it does not readjust to the dimensions of the element it was highlighting. In simple words, it isn't "Responsive".

**Comment by sysUser1** [comment]
Quick fix for this issue is to go to bootstrap-tour.js and in function showPopoverAndOverlay, when calling _showOverlayElement, set force to true (line 336 in v0.10.2).

_this._showOverlayElement(step, true);

this way every time showStep is called it will recalculate backdrop size.

**Comment by sorich87** [comment]
Fixed in latest master.
