### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by RWOverdijk** [sorich87/bootstrap-tour#496]
Hi.

I've tried getting this plugin to work, but it seems impossible. I have jquery, bootstrap, and tour set up. It hasn't shown up once.

http://jsfiddle.net/k7bno401/2/

**Update:** In case you're wondering, I have tried it with the master branch version, too.

**Comment by ousram** [comment]
Do you still have this issue ? I've tried on your jsfiddle http://jsfiddle.net/k7bno401/2/ and it's working. I guess the problem you have it's that the tour just played once and never played again. If you want the tour to always play, you have to use the restart() method insert of start(), or you can force the start too.

**Comment by RWOverdijk** [comment]
Hello @ousram 

~~Nope it's still not doing anything. Not even once. The only place I've seen it working has been the website haha.~~

Ah. It stores the fact that it has run in the past. I did not know that. Thanks :)
