### ISSUE TITLE
Wrong management of bower dependecy

### ISSUE THREAD

**Issue by thedarkdestructor** [sorich87/bootstrap-tour#503]
Hello. I'm using bootstrap-sass in conjunction with bootstrap tour. The problem that I am facing is that bower.json of bootstrap-tour declare a dependency on bootstrap. This cause me of having bootsrap download two times.

{
  "name": "bootstrap-tour",
  "version": "0.10.1",
  "main": [
    "./build/js/bootstrap-tour.js",
    "./build/js/bootstrap-tour-standalone.js",
    "./build/css/bootstrap-tour.css",
    "./build/css/bootstrap-tour-standalone.css"
  ],
  "dependencies": {
    "bootstrap": ">=2.3.2",
    "jquery": ">=1.9.0"
  },
  "devDependencies": {
    "html5shiv": "~3.7.2",
    "jquery": "~2.1.1",
    "bootstrap": "~3.2.0",
    "blueimp-md5": "~1.1.0"
  }
}

There is a way to specify a different dependency for bootstrap-tour?

**Comment by ousram** [comment]
Bootstrap tour have to keep bootstrap in its dependencies.
As you already have bootstrap, maybe you can update your own bower.json
