### ISSUE TITLE
Using the Tour between Tabs

### ISSUE THREAD

**Issue by rvbz** [sorich87/bootstrap-tour#504]
Hello, good day,

I have a page using Tabs, the deal is that I initiate the tour in the first tabs that it's shown by default and no problem in here, but when I need to go to other tab to continue the tour, the tour stops and disappear.

Does anyone can help me?

**Comment by ousram** [comment]
Does the url change when you click on another tab ?

**Comment by mabm** [comment]
You have to use "onNext" callback for the step placed before your tab changing ! And in this function, you have to write some JS to allow to switch your tab ;)

**Comment by rvbz** [comment]
I just figure it out, the step doesn't shows if the dom element if not visible, so when I change between tabs the animation process makes the dom element display after the code execution, so no tor step were showing, I just needed to add a little delay with the delay property and voila.
Thanks.
