### ISSUE TITLE
onEnd doesn't fire when clicking very last Next button

### ISSUE THREAD

**Issue by RushRuin** [sorich87/bootstrap-tour#509]
If a user clicks the Next button (which is disabled) on the very last tour item the onEnd event does not fire. The tour does appear to end, it goes away, but the event is not fired.

**Comment by ousram** [comment]
Hello @RushRuin 
Why do you want "clicking on last Nexxt button to end tour" ?
I think the "End tour" button, is pretty ok.

**Comment by RushRuin** [comment]
When a tour is on its last step there is a "Next >>" button next to a "Quit Tour" button, just like always. The "Next >>" button is "disabled", but if you click it, which 99% of people will do, the tour ends but the onEnd doesn't fire.

**Comment by ousram** [comment]
No, I don't think that's too much important or necessary.
The last "Next  button" and the first "Prev button" are clearly disabled (greyed out).
It doesn't make sense, If a click on disabled button triggers any action.

**Comment by RushRuin** [comment]
I'm not sure you understand. When you click the (supposed) disable last "Next" button it **already** triggers an action of closing the tour. I'm not asking for this to be added. My bug report is that it should trigger onEnd as well as closing the tour. It's a very simple issue. If anyone thinks it should not trigger onEnd than I'd argue that it shouldn't close the tour. So I would say that's a bug.

**Comment by sorich87** [comment]
Yes, it's a bug that was fixed a few days ago. https://github.com/sorich87/bootstrap-tour/issues/467
