### ISSUE TITLE
Create a 0.10.13 release

### ISSUE THREAD

**Issue by SCdF** [sorich87/bootstrap-tour#510]
The last release on npm (0.10.11) was over a year ago, and it looks like the latest release not on npm (0.10.12) has issues. It would be good to bundle up the current code and release 0.10.13 to NPM.

**Comment by ousram** [comment]
This is already done !
Thanks

**Comment by SCdF** [comment]
Cheers @ousram! Is it built from the current master? I'm not seeing a tag on github

**Comment by ousram** [comment]
Yes it is. You'll be abble to see it now.
