### ISSUE TITLE
Delay object not supported

### ISSUE THREAD

**Issue by sergiubologa** [sorich87/bootstrap-tour#512]
[The documentation](http://bootstraptour.com/api/) says that the `delay` option can be a boolean, a number but also an object containing optional `show` and `hide` options. As I saw in the source code this is not yet supported. Is this a bug or the documentation is ahead of its time?

**Comment by ousram** [comment]
Hi @sergiubologa , the delay option is available and it works well.
I guess you got the library by npm. There was a bug, so installing by npm used to provide the 0.10.1 version. This is fixed now, so install it again and you'll get the newest version : 0.10.3

**Comment by sergiubologa** [comment]
@ousram great, thank you for your answer.
