### ISSUE TITLE
Issue on Demo website [redirect issue]

### ISSUE THREAD

**Issue by manu1222** [sorich87/bootstrap-tour#513]
Below is my code:
$(function() {
    var tour_15 = new Tour({
        name: 'tour_15',
        debug: false,
        steps: [{
            "path": "url 1",
            "element": ".subnav > table:eq(0) tr:eq(6)",
            "title": "Welcome to FA",
            "content": "FA Description here."
        }, {
            "path": "url 2",
            "element": "a[target$=help_page]",
            "title": "Click here for HELP",
            "content": "Help Description"
        }]
    });
    tour_15.init();
    tour_15.start();
});

So if I click on next button it will redirect me to 'url 2' , and now if I try to access 'url 1' directly, I'm unable to access it as it will redirect it back to 'url 2' and similarly if I click on prev from 'url 2' then I'm unable to access 'url 2' as it will keep on redirecting back to 'url 2' if I try to access 'url 2' direclty.

Steps to check it on http://bootstraptour.com are as below:
1) click on 'start the demo' then keep on clicking next until you gets redirected to other url that is http://bootstraptour.com/api/
2) Now just change the url from http://bootstraptour.com/api to http://bootstraptour.com . It will redirect it back to http://bootstraptour.com/api.

**Comment by ousram** [comment]
Hi @manu1222 , that's the way BootstrapTour works.
It considers, you didn't end the tour, so it always take you back to the last page or the last step you saw.
Just click on ''End tour", and it's done !

**Comment by rubengrb** [comment]
uuu<b>uu<b>

**Comment by manu1222** [comment]
@ousram Ok got you. I didn't think it that way. Its fine.
