### ISSUE TITLE
Stray "</nav>" in template on API Documentation page

### ISSUE THREAD

**Issue by benomatis** [sorich87/bootstrap-tour#517]
On the [API Documentation](http://bootstraptour.com/api/) you have a stray `</nav>` in the template on top under Global Options:

```
template: "<div class='popover tour'>
    <div class='arrow'></div>
    <h3 class='popover-title'></h3>
    <div class='popover-content'></div>
    <div class='popover-navigation'>
        <button class='btn btn-default' data-role='prev'>« Prev</button>
        <span data-role='separator'>|</span>
        <button class='btn btn-default' data-role='next'>Next »</button>
    </div>
    <button class='btn btn-default' data-role='end'>End tour</button>
    </nav>
  </div>",
```

See before last line.

This seems to be correct further down, and is also they way the code has been written.

I know this is not directly related to the code itself, but I found no better way of notifying you. Hope this helps.

**Comment by ousram** [comment]
Thank you @benomatis. It will be fixed.
