### ISSUE TITLE
query params on path

### ISSUE THREAD

**Issue by realves** [sorich87/bootstrap-tour#518]
Hi,  how i can use path like this:

I start in home with this path:
/
Good! 

Next step is;
**/?page=utility**
And other is:
**/?page=other**

At this moment, all steps with GET parameters are ignored because elements doesn't exists... on path /

I hope that you'll help me!!!

Thanks!

**Comment by ousram** [comment]
Hi @realves ,
This kind of links look like Single page app links.
But single page apps are not supported yet !
