### ISSUE TITLE
Highlighted area not display

### ISSUE THREAD

**Issue by ovaiskhan11** [sorich87/bootstrap-tour#520]
I am using your plugin but I have faced some issues. The highlighted area becomes completely white. I am guessing that this is some CSS conflict because I am using bootstrap.

What can I do to determine the cause of this problem?
![bootstrap_tour_issue](https://cloud.githubusercontent.com/assets/14327377/13210951/a2510846-d94d-11e5-83a6-4b4e13e17f64.png)

**Comment by realves** [comment]
Hi! I think this is a z-index issue...
Inspect html code. Find current step element and set z-index value manually to Fix. 

If it is fixed, then apply css rule updating z-index value for this element.

**Comment by ddeath** [comment]
I have fixed element an adding z-index to it does not help.

**Comment by realves** [comment]
Maybe your z-index value is too lower... Can you post your site url?
Il 23/Feb/2016 09:50, "Dušan Plavák" <notifications@github.com> ha scritto:

**Comment by ddeath** [comment]
Sorry I can not, it is private. I tried all ranges of z-index non of them worked. I will try to create some mini example when I will have more time. Thanks

**Comment by ovaiskhan11** [comment]
I have fixed the issue. My custom bootstrap css was conflicted with your css. I just removed position:absolute in my css

**Comment by ddeath** [comment]
@realves Hi there, I created code pen where it is "not working" or at least I am doing something wrong.
http://codepen.io/Ddeath/pen/LGwjzj
