### ISSUE TITLE
Backdrop is covering elements  when used on fixed elements

### ISSUE THREAD

**Issue by ddeath** [sorich87/bootstrap-tour#522]
Hi there, I created code pen where it is "not working" or at least I am doing something wrong.
http://codepen.io/Ddeath/pen/LGwjzj

**Comment by Thoum** [comment]
+1 Same problem here on a nav ul li.

**Comment by rgbskills** [comment]
+1 Same problem

**Comment by rgbskills** [comment]
Here is a quick fix:
{
    element: "#my-element",
    title: "Menu item",
    content: "This is a menu item",
    onShow: function(){
      $('.sidebar').addClass('sidebar-tour-fix');
    },
    onHide: function(){
      $('.sidebar').removeClass('sidebar-tour-fix');
    },
  },

.sidebar is my fixed element.
.sidebar-tour-fix{
    position:absolute;
    z-index: initial;
}

It's an ugly quick fix :))

**Comment by earllapura** [comment]
+1 Same problem here!

**Comment by sorich87** [comment]
Duplicate #152

**Comment by exhtml** [comment]
+1, would be good to fix it. Thank you!

**Comment by schx2** [comment]
+1
