### ISSUE TITLE
Manual hash redirect breaks tour redirects.

### ISSUE THREAD

**Issue by kwstoikonomou** [sorich87/bootstrap-tour#532]
i have the following steps in my Tour: 
```javascript 
steps: [
                {
                    orphan: true,
                    title: "Welcome!",
                    content: "Let us show you around.",
                },
                {
                    element: "#newButton",
                    placement: "left",
                    title: "You can start from here!",
                    content: "Click to create.",
                    path: '/#/index/1',
                },
                {
                    element: "#someElement",
                    title: "Element",
                    content: "Element",
                }]
```
The following actions break the Tour functionality:

<table>
<tr>
<th>Action</th>
<th>Expected Behavior</th>
<th>Actual Behavior</th>
</tr>
<tr>
<td>Load Page at: /#/index/2</td>
<td> Tour Starts</td>
<td> Tour Starts</td>
</tr>
<tr>
<td>Click Next</td>
<td>Redirect to /#/index/1, step 2 is diplayed</td>
<td>Redirect to /#/index/1, step 2 is diplayed</td>
</tr>
<tr>
<td>Click Previous</td>
<td>Step 1 is diplayed</td>
<td>Step 1 is diplayed</td>
</tr>
<tr>
<td>ManuallyChange hash to /#/index/2</td>
<td>Redirect to /#/index/2, Step 1 is diplayed</td>
<td>Redirect to /#/index/2, Step 1 is diplayed</td>
</tr>
<tr>
<td>Click Next</td>
<td>Redirect to /#/index/1, Step 2 is diplayed</td>
<td>**No redirect happens, Step 3 is diplayed**</td>
</tr>
</table>

This happens because of this lines of code inside Tour._redirect():
```javascript 
else if (step.redirect === true) {
                this._debug("Redirect to " + step.host + path);
                if (this._getState('redirect_to') === ("" + i)) {
                    this._debug("Error redirection loop to " + path);
```
the following check is true: ```javascript if (this._getState('redirect_to') === ("" + i)) { ``` and as a result the function returns. I don't know why this check happens but i seems like manual redirects have not been predicted.

**Comment by sorich87** [comment]
Should be fixed in latest master.
