### ISSUE TITLE
white space in backdrop

### ISSUE THREAD

**Issue by js-people** [sorich87/bootstrap-tour#534]
Hi;
My top navbar is fixed position. but when I enable backdrop I see white space.
http://colorclass.ir/pic.JPG

**Comment by vicentor** [comment]
I can't see the screenshot, but I'm pretty sure I have the same issue. When the backdrop is enabled, the background becomes darker, but the selected element has a while (no transparency) div (class="tour-step-background") on top of it.

**Comment by webresh** [comment]
You can see it in this [pen](http://codepen.io/SaraVieira/pen/rDKkj/)
it is highlighted only when object is an image, otherwise transparent background over z-index is not working.

**Comment by js-people** [comment]
It is a good idea!
Thanks.

**Comment by sorich87** [comment]
See #183. A better solution is being worked on.
