### ISSUE TITLE
top placement disables buttons

### ISSUE THREAD

**Issue by jaritt** [sorich87/bootstrap-tour#539]
When I use the "placement: top" option for a step and the element is already pretty high on the webpage, the step is not displayed correctly (which is no problem so far), but also the buttons are not clickable any more. It is the first step in the tour.
I used the following code:
`   {
      "title":"Test_title",
      "content":"<p>Test_content</p>",
      "element":"#jumbotron",
      "placement":"top",
      "path":"/",
      "backdrop":true
   }`
 
Greets

**Comment by sorich87** [comment]
Can't reproduce.
