### ISSUE TITLE
The element of step didn't centered on the screen

### ISSUE THREAD

**Issue by rgalaxy** [sorich87/bootstrap-tour#540]
`var tour = new Tour({
		        steps: [
		        	{
			            element: ".must-read",
			            title: "Title of my step",
			            content: "Content of my step",
			            placement: "right"
		          	},
		          	{
			            element: ".introduction-box",
			            title: "Title of my step",
			            content: "Content of my step",
			            placement: "top"
		          	},
		          	{
			            element: ".cool-op-list",
			            title: "Title of my step",
			            content: "Content of my step",
			            placement: "bottom"
		          	},
		          	{
			            element: ".socmed-share",
			            title: "Title of my step",
			            content: "Content of my step"
		          	}
		        ],
		        autoscroll: true,
		        debug: true,
		        backdrop: true
	    	});
	    tour.init(true);
	    tour.start(true);
		});`

Hello, i have trouble using bootstrap tour plugin.
everything went great, except the step did not centered the "step" that currently running.

 **here you can see that the first step works just fine.**
![xxxx](https://cloud.githubusercontent.com/assets/18610548/14735166/99183b66-0899-11e6-9812-9a7634e8306c.PNG)

**and then when i go to second step, the viewport didnt move, so the content gets too low..**
![yyyy](https://cloud.githubusercontent.com/assets/18610548/14735170/a3b5a5b8-0899-11e6-90a2-56b63ce94fff.PNG)

**and then i put step3 far more bottom as you can see on the 4th pic. but the viewport only scroll to the middle of the web (as you can see on the scrollbar at 3rd pic)**
![zzzzz](https://cloud.githubusercontent.com/assets/18610548/14735180/ac74d138-0899-11e6-8834-7c3e0e314f3f.PNG)
![aaaaa](https://cloud.githubusercontent.com/assets/18610548/14735182/b1c1d974-0899-11e6-97d4-4c1ce4e52d26.PNG)

is there anyway to know what is wrong? maybe my content too long or something? do i need to specify the scrollTop() thing ? 
i've tried to add the "debug" thing but still couldn't understand what is wrong.. 

Thank you before :+1: :smiley:

**Comment by rgalaxy** [comment]
i've find the solution even though this solution is somewhat so bad
i changed `scrollTop = Math.max(0, offsetTop - (windowHeight/2));` into `scrollTop = Math.max(0, offsetTop - 300);`

i realize when i debug it, it calculates my window height as 4000++ and that's why the calculation of scroll isn't right. i hope you will fix this. thank you

**Comment by sorich87** [comment]
Fixed in d78c318af991bd88fa58a5c7c611442de2ae1ef3.
