### ISSUE TITLE
Multi page traversal Tour stops working after loading page for next step in php

### ISSUE THREAD

**Issue by shanibadezigndenie** [sorich87/bootstrap-tour#543]
I have include this code into main js file. 2 steps are working proper. the third step is after page load but after page loads these 2 steps only working. am new to bootstrap tour. 

`    var tour = new Tour({
        storage : false
    });
        tour.addStep({
            element: ".tour1", /* html element next to which the step popover should be shown */
            placement: "top",
            title: "Step 1", /* title of the popover */
            content: "Upload your profile image here" /* content of the popover */
        });
        tour.addStep({
			element: "#changeCoverPhoto",
            placement: "left",
            title: "Step 2",
            content: "Upload your background image from here."
        });
       		tour.addStep({
			element: "#sidebar",
            placement: "bottom",
            title: "Step 3",
            content: "Visit your front end from here.",
			path:"<?php echo $tourpath;?>"
			
        });
			tour.addStep({
			path:"<?php echo SITE_URL."projects"; ?>",
			element: ".tour4",
            placement: "bottom",
            title: "Step 3",
            content: "Visit your front end from here."
        });
		tour.init();
        tour.start();`

**Comment by furqanaziz** [comment]
If you have added this code to your main.js file then it could not have php code in it.

**Comment by shanibadezigndenie** [comment]
NOp I have added this code in to the footer.php where i can get all variables.

**Comment by yupe** [comment]
Same problem as @shanibadezigndenie , steps with path are reload page and start tour from start

**Comment by sorich87** [comment]
`storage` option should be set to true for it to work in this case.
