### ISSUE TITLE
"tour_end" doesn't show in Local Storage on Firefox

### ISSUE THREAD

**Issue by michalkopanski** [sorich87/bootstrap-tour#548]
After completing the tour in Chrome, `tour_end` is set to `yes` in Local Storage, and can still be seen after refreshing. When opening Firefox, only the `current_step` is available in Local Storage. `tour_end` is not.

This causes the tour to re-launch in Firefox from the step saved in Local Storage, which is not the desired effect.

**Comment by sorich87** [comment]
Can't reproduce.
