### ISSUE TITLE
[iphone] Backdrop stays above after the tour ends, disabling all elements below

### ISSUE THREAD

**Issue by tinyCoder32** [sorich87/bootstrap-tour#550]
Thanks for the incredible plugin, after the tour ends on my iphone the backdrop stays there, it never get hidden, but stays there preventing me from clicking any other element on the page.

is there a fix for that please?

Thanks.

**Comment by sorich87** [comment]
A new way to handle backdrop has been implemented in 7f98180015f02231f5e9b9689785413fbe070454. Please test.
