### ISSUE TITLE
LocalStorage browser support

### ISSUE THREAD

**Issue by JoelMendoza** [sorich87/bootstrap-tour#556]
Greetings, this a great plugin, thanks for all of the hard work.  This is more of a question, how does bootstarptour handle a browser that does not support localstorage?  Does it start every time the page is loaded?

**Comment by JoelMendoza** [comment]
The goal is to not have the tour every time the page loads for browsers that do not support localstorage.  After thinking about this, it looks like I can do tour.init(), and check for local storage support:

        if (typeof (Storage) != "undefined") {
            tour.start();
        }

Any thoughts?

**Comment by sorich87** [comment]
You can create your own storage object with properties `setItem`, `getItem`, `deleteItem` and handle storage the way that suits you.
