### ISSUE TITLE
getCurrentStep() in title of a step? 

### ISSUE THREAD

**Issue by gabn88** [sorich87/bootstrap-tour#559]
As mentioned in https://github.com/sorich87/bootstrap-tour/issues/379 issue, if the last step in an orphan, the tour will not end correctly. But also it was to me unclear how exactly bootstrap-tour was doing with orphaned steps, and it seems to skip them. A valid thing to do of course, but the only thing is that users might miss a whole part of the tour. Just to notify the users of the step they are I would like to show the current step in the title, is this possible?

**Comment by aslamkhan669** [comment]
Yes just edit the popover template of the tour and you can display whatever you like.
