### ISSUE TITLE
Cross Domain Functionality

### ISSUE THREAD

**Issue by aslamkhan669** [sorich87/bootstrap-tour#564]
I am facing issue in creating a tour having cross domain functionality. my tour does not run if domain is changed. Also I can overcome this issue by using chrome storage but bootstrap tour uses window.localstorage which is preventing me to share data across domains. Any suggestion or help is appreciated.

**Comment by brexis** [comment]
@aslamkhan669 I think what you need is a cross domain storage. You can try this https://github.com/tekxl/bootstrap-tour-extras

**Comment by sorich87** [comment]
@aslamkhan669 you can use what @brexis suggested or you can roll your own storage object.

**Comment by aslamkhan669** [comment]
@sorich87 Its not working for two different domains.

**Comment by sorich87** [comment]
@aslamkhan669 then you can roll your own solution using Chrome Storage as you mentioned. You just need to create an object with `setItem`, `getItem` and `deleteItem` properties like @brexis did.
