### ISSUE TITLE
Support SVG element?

### ISSUE THREAD

**Issue by guidorice** [sorich87/bootstrap-tour#565]
Hi, I am having a tough time getting bootstrap-tour to step through SVG sub-elements (d3js charts actually). I noticed the code is detecting the presence svg by the namespaceURI property:

```
  _isOrphan: (step) ->
      # Do not check for is(':hidden') on svg elements. jQuery does not work properly on svg.
      not step.element? or
      not $(step.element).length or
      $(step.element).is(':hidden') and
      ($(step.element)[0].namespaceURI isnt 'http://www.w3.org/2000/svg')
```

re: namespaceURI, according to mdn:

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

https://developer.mozilla.org/en-US/docs/Web/API/Node/namespaceURI

Is this the reason why bootstrap tours does not work with SVG, or are there other problems? The comment suggests maybe a problem with jQuery. Please advise if there are any known issues with SVG or what you recommend. Thanks so much!

**Comment by guidorice** [comment]
Here is a simple example which shows how bootstrap-tour breaks down trying to go to svg elements:
https://gist.github.com/guidorice/c7fdc7fe4b4aacc25677c41aa479980b

**Comment by guidorice** [comment]
Actually we realized after I logged this issue, this could only be a problem in  latest version of chrome (52.0.2743.116) ... Firefox does the right thing, and Safari does well, kinda sorta the right thing. Please let us know if you have any related info, or hints, or just close this. Thanks

**Comment by sorich87** [comment]
@guidorice do you mean it works on IE, Firefox and Safari? but not Chrome?

**Comment by guidorice** [comment]
@sorich87 sorry I was not clear. In IE11 and Firefox, it looks fine. I tried the above gist on latest chrome 52 stable and 53 beta. Here is what it looks like.

![bootstrap-tour](https://cloud.githubusercontent.com/assets/766758/17410058/4aee5d0c-5a2f-11e6-8e8b-5eaa4b5e224d.jpg)

Then I tried downgrading jquery from 3.1.0 to 2.2.4, then it appeared slightly better, but the steps were still mispositioned in chrome.

In Safari 9.1.2 - it looks slightly amiss, rect1 and rect2 have the exact same tip placement, which doesn't seem quite right.

**Comment by sorich87** [comment]
@brexis please what jQuery version did you use it with SVG?

**Comment by sorich87** [comment]
@guidorice Are you using Bootstrap 3.3.7? Maybe it's the same issue as https://github.com/twbs/bootstrap/pull/20313 that's fixed in 3.3.7?

**Comment by guidorice** [comment]
@sorich87 Ah that does sound like it could be the issue. I have been using bootstrap-tour-standalone (so whatever bootstrap version that comes bundled with?)

**Comment by sorich87** [comment]
It was 3.2.* Just upgraded to 3.3.7. Please try.

**Comment by guidorice** [comment]
@sorich87 , confirmed this issue is fixed in Safari and Chrome. Thanks so much all!

**Comment by guidorice** [comment]
@sorich87 would it be possible to make a new release? I like to use cdnjs, and the last release is 0.10.3 on there. Thanks!
