### ISSUE TITLE
How to restart the tour from the first step once it has ended normally?

### ISSUE THREAD

**Issue by Amenel** [sorich87/bootstrap-tour#590]
I have implemented a 13-step tour in a current project. The tour that can be started by clicking a "Start the tour" button. However, I realized that once the tour is over, clicking the button again does not launch a new tour.

I have used `start(true)` but then, the tour starts again at the very last step.

I have then used `debug: true` in the options of the tour, this is what I see in the console: 

    Bootstrap Tour 'tour' | Tour ended, init prevented.
    Bootstrap Tour 'tour' | Tour ended, showStep prevented.

Disabling local storage altogether with tour option `storage: false` will cause losing the ability to restart at step X when the tour was interrupted at step X. Aside from disabling local storage altogether, is there a possibility to have the tour restart from step 0 once it has ended normally with step N?

Thx.

**Comment by paulnthompson84** [comment]
Have you tried restart() instead of start(true)?

**Comment by Amenel** [comment]
`tour.restart()` is the answer! I was using it in the `onHidden` function of the last step, and on the `onEnd` method of the tour itself, but the result was a tour that was looping.

Instead of `tour.start()`, I am now using `tour.restart()` in the click handler of my "Start the tour" button. 

Many thanks to the person who sent me the question about `restart` via e-mail.

**Comment by jonalxh** [comment]
Thanks a lot, it helped me after a lot of time.
