### ISSUE TITLE
Stop() Command

### ISSUE THREAD

**Issue by roryok** [sorich87/bootstrap-tour#591]
I have Bootstrap Tour set up so that the tour is not shown when in resolutions below 768px, as it doesn't work well with the hamburger menu (in my layout). I'd like to stop the tour when the user resizes to 767px or lower. However, if I `.end()` the tour, won't that lose the user's position? 

Since there is a `start()` command, should there be a corresponding `stop()` command along with `end()`

**Comment by sorich87** [comment]
No, `.end` doesn't lose the user's position. You can use `start(true)` to continue after end.
