### ISSUE TITLE
Multi-element selectors

### ISSUE THREAD

**Issue by psema4** [sorich87/bootstrap-tour#600]
Is it possible to show only one tour step when using a selector that returns multiple elements?  In my use case we have a table with some TD's in each TR used to track the progress of a students through a course.  We'd like to show one tour step, but highlight each of the relevant TD's:

![bootstrap-tour-multi-element-selector](https://cloud.githubusercontent.com/assets/130183/21151831/f4709cc8-c131-11e6-90ff-babc5ec38b29.png)

**Comment by elkouo** [comment]
+1
I have exactly the same problem

**Comment by ralphjay24** [comment]
Hi bootstrap tour team. I'm sorry I'm a beginner with your plugin and also not skillful in terms of JQuery. May I ask if this is really a bug in your system? When I try to specify the step element to `table tr td:nth-child(-n+3)`, it will highlight the first three columns but the popover will display in 3 times(same issue above). I don't know if I'm just noob with this but may I confirm about this one. Thank you!

**Comment by akriti7** [comment]
is it possible to have two different div elements highlighted but tour guide to be shown only on one?

**Comment by Aggelost1** [comment]
what is the statues on this question it seems a useful feature but i cant find an answer anywhere.

So is it possible to have two different div elements highlighted but tour guide to be shown only on one?

**Comment by Bill-TEGNA** [comment]
Having same issue.  I would like multiple td cells highlighted with only tour window for both.

**Comment by EtagiBI** [comment]
> is it possible to have two different div elements highlighted but tour guide to be shown only on one?

It's a really useful feature indeed!

**Comment by mrsarm** [comment]
Having the same problem, CSS is not as powerful as XPath selectors, so `:first-child` not always solves the problem, and you are not always allowed to change the markup of what your are showcasing with the tour guide, so a new configuration property `onlyFirstElement: true` (default `false`) would be useful.
