### ISSUE TITLE
Materilalize tooltip not working if bootstraptour.js used in angular app

### ISSUE THREAD

**Issue by Subbu033** [sorich87/bootstrap-tour#608]
In my materialize app, I have used bootstrap tour for a button when I click on it. Also, the button has materialize tooltip. The toolitp is not working when **bootstrap-tour-standalone.min.js** used. 

Please check my [fiddle](https://jsfiddle.net/subramanian/7cjm4jLe/). Please check this after removing **bootstrap-tour-standalone.min.js**. The tooltip will work!
Not only for the button, the other tooltips wherever I have in the entire page are not working, .  

Help please!

**Comment by giovanniorigins** [comment]
My guess is that this is because they both use $.fn.tooltip, I would suggest trying to use it in `no conflict mode` or finding a tour plugin that complements the materialize framework

**Comment by SimonMuraya** [comment]
You can place the 

> <script src="bootstrap-tour-standalone.min.js"></script>

 before 

> <script src="materialize.min.js"></script>

**Comment by Subbu033** [comment]
Cool! That works for me @SimonMuraya ! Thanks a lot :)
