### ISSUE TITLE
How to force left side tour display?

### ISSUE THREAD

**Issue by WriterStat** [sorich87/bootstrap-tour#618]
Need to force left side tour display for items on right side of our page menu.

example: Let's say you have 3 icons close together on the right side of your top menu near the page side. The tour displays to the right of the first icon just fine. Then after that it continues to display in the exact same place pointing at the same icon. But with different text.

Because it displays on the right it basically covers the icon it should be pointing at, instead of auto switching over to the left side and pointing from the left hand side to the correct icon.

How to force left side tour display?

Much Thanks!

**Comment by rltorres06** [comment]
I was having the same issue and found this post
https://github.com/sorich87/bootstrap-tour/issues/120

**Comment by WriterStat** [comment]
Cool! Will give it a whirl. Guess I never thought of using the bootstrap defaults. Figured it would be a tour setting. Thanks!

**Comment by Tranhongminh090** [comment]
Hola, qué tal. . " Tiểu Ngọc rồng. " " " type. El tema del que me llamen.
