### ISSUE TITLE
Show only 1 or 2 elements

### ISSUE THREAD

**Issue by fcdeveloper** [sorich87/bootstrap-tour#620]
If I have elements with the same ID the popover appear as many id I have.. is possible to limit the amounts of popover to show.
Thank You
https://cl.ly/2T301m0z1Y31

**Comment by ousmanedev** [comment]
First, you shouldn't have several elements with the same ID. IDs are meant to be unique. You should use classes instead.
However, you can use `element: 'my-id:eq(index)'` with `index` being your element's index (starting from 0).
https://api.jquery.com/eq-selector/

**Comment by fcdeveloper** [comment]
Thank You it works for me.
