### ISSUE TITLE
Tour does not work if name contains spaces

### ISSUE THREAD

**Issue by sh977218** [sorich87/bootstrap-tour#633]
If the tour's name has space in it. Tour will not work. My assumption is the local storage retrieve the value using the dot notation (  localStorage.key ).  If key has space in it, game over. It should be  localStorage[key].

**Comment by Pamblam** [comment]
Finding this issue helped me solve my own problem so thank you, however, the docs do explicitly say [spaces are not allowed](http://bootstraptour.com/api/):

> The name should contain only alphanumerics, underscores and hyphens.

**Comment by sh977218** [comment]
My assumption is that is using  {}.key  instead of  {}[key].  because [key] will work with key that has space, but  .key will not. Thank you for letting me know that API says it.  I'll close this.

**Comment by Pamblam** [comment]
you can't use dot notation with variable names ;) it *has* to be using square brackets or it wouldn't be working at all
