### ISSUE TITLE
bootstraptour.com is down

### ISSUE THREAD

**Issue by fdvmarkus** [sorich87/bootstrap-tour#639]
I'm not sure if this is the right place to report it, but it appears that bootstraptour.com has vanished from the Internet. This is problematic, because that's where the documentation for bootstrap-tour is located.

**Comment by andruschka** [comment]
+1

**Comment by oleghalin** [comment]
+

**Comment by danparnella** [comment]
+1

**Comment by vesper8** [comment]
yep still down

**Comment by sorich87** [comment]
It's back! Sorry for the inconvenience.
