### ISSUE TITLE
end tour when you click on backdrop (or outside modal if no backdrop)

### ISSUE THREAD

**Issue by vesper8** [sorich87/bootstrap-tour#641]
just trying to do something seemingly basic.. I want to allow users to discard the tour by simply clicking outside the tour modal

doing the following 

```
              tour.init();
              tour.start();

                $(".tour-backdrop").on("click", function (e) {
                  tour.end();
                });

```

I was able to get it to work but oddly it only works when you click the backdrop on the very first step, not on subsequent steps

it also wouldn't work if you don't use a backdrop

anyone know a better solution?

thanks!

**Comment by Enchiridion** [comment]
I haven't tested this yet, but my guess is the backdrop element is getting destroyed/recreated with each step, so that's why your listener on works on the first step. You'll need to bind to the body element and filter for the tour-backdrop class.

`$('body').on('click', '.tour-backdrop', function(){});`

**Comment by aslamkhan669** [comment]
Pretty easy i guess use my code to end it whenever user clicks outside pop-up tour ends.
```
 jQuery('html').on('mouseup', function (e) {
                if (!$(e.target).closest('.popover').length) {
                    jQuery('.popover').each(function () {

                        tour.end();
                    });
                }
            });
```

**Comment by vesper8** [comment]
thanks @Enchiridion your suggestion works

**Comment by alex-fe** [comment]
(For future visitors)
I liked @aslamkhan669's solution, but modified it for personal clarity. 
`.tour-tour` is the tour popover container, hence if the tour is running and click not in container, end the tour. I found checking against the container is more robust, as `.tour-backdrop` may not necessarily be drawn

```javascript
if (!$(e.target).parents('.tour-tour').length && $(".tour-tour").length) {
    ...
    tour.end();
}
```
