### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by lorrandavid** [sorich87/bootstrap-tour#650]
I'm trying to set-up a tour for my website but I'm get a bunch of "Error redirection loop to [URL]", I don't know what's wrong because I'm using the code used on the demo, I also tried to do it by myself but I can't get it right.

This is the code I have on right now:

```
<script type="text/javascript">
    // define tour
    var tour = new Tour({
        debug: true,
        steps: [
            {
                element: "#my-element",
                title: "Title of my step",
                content: "Content of my step"
            },
            {
                element: "#my-other-element",
                title: "Title of my step",
                content: "Content of my step",
                path: "http://www.url.com/page2"
            }
          ]
        });

    $(document).ready(function() {
        // init tour
        tour.init();
        tour.start();
    });
</script>
```

Then I get this error:

> Bootstrap Tour 'tour' | Redirect to http://www.url.com/page2

> Bootstrap Tour 'tour' | Error redirection loop to http://www.url.com/page2

Does anyone know how to solve it? Thanks!

**Comment by lorrandavid** [comment]
* I'm using Laravel

**Comment by lorrandavid** [comment]
So, after hacking a few hours, I got it working by changing the source code from `bootstrap-tour.min.js`. I know it's not ideal but I don't have the time to wait an answer. Here's what I did if anyone is interested: 

First I switched the default:
```
if (step.redirect && this._isRedirect(step.host, path, document.location)) {
  this._redirect(step, i, path);
  if (!this._isJustPathHashDifferent(step.host, path, document.location)) {
    return;
  }
}
```
For:
```
var sameURL = document.URL !== path ? false : true;        
if(!sameURL){
  this._redirect(step, i, path);
  if (!this._isJustPathHashDifferent(step.host, path, document.location)) {
    return;
  }            
}
```

Second, and lastly, I changed the original redirect function:
```
if ($.isFunction(step.redirect)) {
  return step.redirect.call(this, path);
} else {
  href = {}.toString.call(step.host) === '[object String]' ? "" + step.host + path : path;
  this._debug("Redirect to " + href);
  if (this._getState('redirect_to') === ("" + i)) {
    this._debug("Error redirection loop to " + path);
    this._removeState('redirect_to');
    if (step.onRedirectError != null) {
      return step.onRedirectError(this);
    }
  } else {
       this._setState('redirect_to', "" + i);
       return document.location.href = href;
   }
}
```
To:
```
var href;
if ($.isFunction(step.redirect)) {
  return step.redirect.call(this, path);
} else {
  href = path;
  return document.location.href = href;
}
```
_Just a warning: I did this way because I had to get this done and I know I'll always redirect the user, for your case it may be different._

**Comment by rodrigoguariento** [comment]
A similar problem: if your pages are in root of your domain, eg. http://your.domain/page.htm, try set your bootstrap-tour with:

> basePath: '/',

And each steps with:

> path: 'page.htm'

Let see other eg. with http://your.domain/us/ny/page.htm, try set your bootstrap-tour with:

> basePath: '/us/ny/',

And each steps with:

> path: 'page.htm'

The **following code won't work** and will cause the loop:

> basePath: '/us/ny/',

And each steps with:

> path: '/page.htm'

The slash at step path will cause the loop.

**Comment by djordje47** [comment]
Hey, @rodrigoguariento your post saved me! Thanks, I was doing a scroll effect on next event function, that's how my tooltip was activated. But with your explanation about basePath, I was able to change my paths to work out-of-box :+1: Thanks! :wink:
