### ISSUE TITLE
TypeError: n.data(...).getTipElement is not a function

### ISSUE THREAD

**Issue by 1Luc1** [sorich87/bootstrap-tour#660]
Hey,

today i updated my yii2 project with 'composer update'. After some testing i found that my yii2 widget https://github.com/MyCademy/yii2-bootstrap-tour, which relies on this component doesn't work anymore. I get this error, if i want to close the modal window or want to move to the next tour step.

Uncaught TypeError: n.data(...).getTipElement is not a function
    at o._showPopover (bootstrap-tour.min.js:22)

may i provide more information?

cheers,
Luc

**Comment by tomheathershub** [comment]
i have the same issue!

**Comment by claudchan** [comment]
Same issue here. Using version bootstrap-tour - v0.12.0.

**Comment by dzhusi** [comment]
Encountered the same problem, had to download from the archive release O_O

**Comment by skybondsor** [comment]
+ 1

**Comment by jennifertigner** [comment]
+1

**Comment by maxodrom** [comment]
+1

**Comment by ethaning** [comment]
+1

**Comment by 1Luc1** [comment]
moved to bootstrap-tourist: https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist
