### ISSUE TITLE
Release v0.12.0 on CDNJS

### ISSUE THREAD

**Issue by adriangibbons** [sorich87/bootstrap-tour#674]
Hi, love this project!

Have been waiting to see the latest release on CDNJS, but hasn't yet appeared... Still v0.11.0 here:

https://cdnjs.com/libraries/bootstrap-tour

**Comment by ptolemybarnes** [comment]
Seems like the latest version of the website [http://bootstraptour.com](http://bootstraptour.com) hasn't been deployed either.

**Comment by Fir3Chi3f** [comment]
Sorta same with NPM, the latest version number is there, but the build folder doesn't actually contain v0.12.0 files #701

**Comment by adriangibbons** [comment]
Seems to be all fixed so this is closed.
