### ISSUE TITLE
Orphan option is false and the element does not exist or is hidden.

### ISSUE THREAD

**Issue by camohub** [sorich87/bootstrap-tour#684]
Can somebody tell me why I get this error: Skip the orphan step 21. Orphan option is false and the element does not exist or is hidden. 
I am really sure the element is real and visible. So how is it possible? Plugin also unexpectedly skips this step which is really magic.  did you hear about try/catch or why you dont set the orphan to true and show the popup with console.log(also on redirect). Where did you learn programming?

**Comment by georgenicholas** [comment]
I'm having the same issue.  Element is clearly in view.  document.getElementById has no problem finding it as well.  Any suggestions?
