### ISSUE TITLE
Scrolling moves popover

### ISSUE THREAD

**Issue by RamIyer1998** [sorich87/bootstrap-tour#712]
Hello! I'm currently writing a tour using bootstrap tour for a data visualization application, and there is one page where the data is visualized as nodes on an SVG. When I add one particular node as a step, I find that the popover moves away from the node as I scroll away (I'm using D3 as the data visualization library). Is there any way to fix this? I tried setting `smartPlacement` to `false` but it doesn't seem to work. I'll try and come up with a code demo soon.
<img width="1103" alt="screen shot 2018-11-28 at 6 07 18 pm" src="https://user-images.githubusercontent.com/17326751/49188385-8fbc4a80-f338-11e8-8775-52ddbae954a4.png">
<img width="1251" alt="screen shot 2018-11-28 at 6 07 28 pm" src="https://user-images.githubusercontent.com/17326751/49188389-921ea480-f338-11e8-8207-0c2f2d89c996.png">

**Comment by IGreatlyDislikeJavascript** [comment]
Try my fork. The original Tour triggers a destroy and recreate of the popover every time you scroll. My fork solves this, and sticks the tour step to the element without any redraw.

Just take the bootstrap-tour.js from my fork, have a look at the added options etc.

https://github.com/sorich87/bootstrap-tour/pull/710

**Comment by RamIyer1998** [comment]
Your fork worked. Thanks!
