### ISSUE TITLE
bootstraptour is down

### ISSUE THREAD

**Issue by OEUSSE** [sorich87/bootstrap-tour#725]

**Comment by OEUSSE** [comment]
Is there another page to see the documentation?

**Comment by r4hulp** [comment]
Even I wanted to have a look at documentation today. Looks like the domain got expired yesterday.

**Comment by ajgarlag** [comment]
You can read it in [archive.org](https://web.archive.org/web/20181028003227/http://bootstraptour.com/api/)

**Comment by tgladney** [comment]
Does anyone know if the site is going to come back up or if the product is going away

**Comment by IGreatlyDislikeJavascript** [comment]
> Does anyone know if the site is going to come back up or if the product is going away

The authors of Tour are still around but don't have the time to maintain it at the moment. 

I've created a fork of Tour that fixes many of the issues reported and features requested. My repo is here:

https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist

And you can read more about why here:

**Comment by sorich87** [comment]
Hi everyone! Very sorry about that. The website is back up again.
