### ISSUE TITLE
module not working with Bootstrap 4.3.1 and JQuery 3.4.1

### ISSUE THREAD

**Issue by senior-js** [sorich87/bootstrap-tour#739]
I see this error:
![Capture](https://user-images.githubusercontent.com/3840173/81549657-58a6f100-9394-11ea-9985-f67ca8332d52.PNG)

**Comment by isaquebezerra** [comment]
Same error here

**Comment by isaquebezerra** [comment]
try this plugin: https://kamranahmed.info/driver.js/

**Comment by senior-js** [comment]
@isaquebezerra Thanks, Although I found the Bootstrap Tourist before.
https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist

**Comment by tacman** [comment]
same.  I switched to Driver.js, and so far it seems to be working well.
