### ISSUE TITLE
how to reference element inside an anchor ?

### ISSUE THREAD

**Issue by jcorreia** [sorich87/bootstrap-tour#78]
Hi,
I have some elements that are inside an anchor( with tab navigation), that are hidden, because the tab is not selected.
bootstrap-tour was not working in such conditions, but as far as i know this https://github.com/sorich87/bootstrap-tour/pull/42 was supposed to fix that, but I can get to work with it.
I´m not sure if my problem is even this because if I use the path property it will reload my page, which I dont want.

I´ve tried this in element option:
element: "#tab#aval"

and with path this:
path: "#tab3",
element: "#aval",

but it didnt worked. 
How can I do it ?
Thanks

**Comment by tongtoanbs** [comment]
When I'm getting current step ``onShow`` I always get the index of the last step
```javascript
 onShow: function (tour) {
     console.log(tour.getStep(tour.getCurrentStep()));
}
```
example: I started with current step 0 then it returned 0, but after that current step 1 then it returned 0...
