### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by sonicradish** [sorich87/bootstrap-tour#9]
The first time I attempted to run this I received a Maximum call stack size exceeded error.

When I traced it through,  as Tour.start() was being called it was initially sending a value to showStep() that was unusually high ( ~ 57000) and it would loop through next() and showNextStep() repeatedly until the stack size was exceeded.

When I added Tour._current = 0 before calling Tour.start() the issue fixed itself and I haven't been able to recreate it and the code works fine now without implicitly setting _current = 0.

Sorry I don't have more information on the cause, but wanted to post this in case someone else encountered the same issue.

Thanks for sharing the code!

**Comment by hagen** [comment]
This is a result of a run condition resulting for the following: do not explicitly supply an element to each step and do not supply anything to the the option orphan. In this scenario, you'll run into the range exceed error. The condition is missed at lines 306-307 in bootstrap-tour.js; you will pick it up if you set debug to true. I think you may need a failsafe condition in there - if an element isn't provided, and orphan is false in the step, and this is the case for all steps, then additional handling is required.

Cheerio, Hagen
