### ISSUE TITLE
If jquery.cookie not included and useLocalStorage not set in Tour constructor, plugin fails silently

### ISSUE THREAD

**Issue by tankchintan** [sorich87/bootstrap-tour#90]
If the cookie plugin is not loaded or included then throw an error in the console or alert. Currently it fails silently when cookie not included AND  useLocalStorage is not set to true.

**Comment by jimmychoxiling** [comment]
Uncaught TypeError: Tour is not a constructor what about this error @tankchintan

**Comment by tankchintan** [comment]
@jimmychoxiling Sorry, I haven't worked on this for past 5.5 years now, so I have the lost thread.
